### ISSUE TITLE
you can not directly start a project with a class library result type

### ISSUE THREAD

**Issue by dajean0104** [Microsoft/Partner-Center-PowerShell#1]
Hi,

I'm trying to test the module but I have the following error:

you can not directly start a project with a class library result type

I'm using visual studio 2017. Thank you.

**Comment by isaiahwilliams** [comment]
Hi @dajean0104, you can install this module directly from PowerShell by performing the following

1. Run the following command from an elevated instance of PowerShell 
  
  ```powershell
  Install-Module -Name PowerShellGet -Force
  ```

2. Close all open instance of PowerShell 
3. Run the following command from a new elevate instance of PowerShell 

  ```powershell
  Install-Module -Name PartnerCenter -AllowPrerelease
  ``` 

If you would like to run this module from an instance of Visual Studio then you will need to configure the debug properties from the PowerShell project. Perform the following to start the module from Visual Studio 

1. Open the Partner-Center-PowerShell solution 
2. Right click on the PowerShell project, in the solution explorer, and then click Properties
3. Click the Debug tab
4. Click the Start external program radio button 
5. Specify the following for the program to be started
  
  ```
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
  ```

6. Specify the following for the Command line arguments 
  
  ```
  -NoProfile -NoExit -Command "Import-Module .\PartnerCenter.psd1"
  ```

Now when you attempt to run the project from Visual Studio it will start an instance of PowerShell and import the module.

**Comment by isaiahwilliams** [comment]
I hope that my response helped. I am going to close this issue, but if you are still having issues please feel free to reopen it. If you are having a new issue please open a new issue.
