### ISSUE TITLE
Error while trying to get a list of products with Get-PartnerProduct 

### ISSUE THREAD

**Issue by KlausPeterRiemer** [Microsoft/Partner-Center-PowerShell#107]
# Steps to reproduce

Execute _Get-PartnerProduct_ with either _CountryCode_ and _Catalog_ or _CountryCode_, _Catalog_ and _Segment_ as parameter.
Example:
`Get-PartnerProduct -CountryCode 'DE' -Catalog 'OnlineServices'`
`Get-PartnerProduct -CountryCode 'DE' -Catalog 'OnlineServices' -Segment 'commercial'`

# Expected behavior

A list of products for the parameters specified.
Additional Info: When using CountryCode and ProductId a single product item can be retrieved successfully.

# Actual behavior

## Result with CountryCode and Catalog
```
PS H:\> [Threading.Thread]::CurrentThread.CurrentUICulture = 'en-US'; Get-PartnerProduct -CountryCode 'DE' -Catalog 'OnlineServices'
Get-PartnerProduct : Value cannot be null.
Parameter name: value
At line:1 char:63
+ ...  = 'en-US'; Get-PartnerProduct -CountryCode 'DE' -Catalog 'OnlineServ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: NotSpecified: (:) [Get-PartnerProduct], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerProduct
```

## Result with CountryCode, Catalog and Segment
```
PS H:\> [Threading.Thread]::CurrentThread.CurrentUICulture = 'en-US'; Get-PartnerProduct -CountryCode 'DE' -Catalog 'OnlineServices' -Segment 'commercial'
Get-PartnerProduct : The method or operation is not implemented.
At line:1 char:63
+ ...  = 'en-US'; Get-PartnerProduct -CountryCode 'DE' -Catalog 'OnlineServ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: NotSpecified: (:) [Get-PartnerProduct], NotImplementedException
    + FullyQualifiedErrorId : System.NotImplementedException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerProduct
```

## Result with CountryCode and ProductId
```
PS H:\> [Threading.Thread]::CurrentThread.CurrentUICulture = 'en-US'; Get-PartnerProduct -CountryCode 'DE' -ProductId 'C5928F49-12BA-48F7-ADA3-0D743A3601D5'

ProductId                            Title               Type           Description
---------                            -----               ----           -----------
C5928F49-12BA-48F7-ADA3-0D743A3601D5 Visio Online Plan 2 OnlineServices
```

# Environment

Module PartnerCenter Version 1.5.1903.5

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by isaiahwilliams** [comment]
Hi @KlausPeterRiemer, 

Thank you for bringing this to our attention. The required code change have been made and are being tested right now. Our hope is to release a minor update today, to address this. Please let us know if you have any other issues.

**Comment by isaiahwilliams** [comment]
Hi @KlausLoeffelmann, 

Version 1.5.1903.6 has been released, which includes a fix for this issue. Please update and let us know if you have any other issues.

**Comment by KlausPeterRiemer** [comment]
Hi @isaiahwilliams,

thanks for the fast deployment of a fix, the Get-PartnerProducts cmdlet works as expected now.  No other issues at the moment ...
