### ISSUE TITLE
Set-PartnerCustomerSubscription -AutoRenew does not change the AutoRenew field

### ISSUE THREAD

**Issue by kevinbasoftcat** [microsoft/Partner-Center-PowerShell#115]
# Steps to reproduce

Connected to Partner Center using the Secure Application Model
https://docs.microsoft.com/en-gb/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

Ran the Set-PartnerCustomerSubscripttion -AutoRenew $false command as per the article
https://docs.microsoft.com/en-us/powershell/module/partnercenter/set-partnercustomersubscription?view=partnercenterps-1.5

The command seems to apply but the AutoRenewEnabled field always stays as True

## Expected behavior

Expected for the AutoRenewEnabled field to change to flase on the selected subscriptionid

## Actual behavior

The AutoRenewEnabled field on the subscription stays as True

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

Windows 10
PS 5.1 17763.

**Comment by kevinbasoftcat** [comment]
Attached is the command being run on a test subscription we have and the output clearly showing that field staying as True. Can someone please update me on why this field does not change.

![image](https://user-images.githubusercontent.com/49310429/57692460-b9470500-763e-11e9-85b9-cdde662180f1.png)

**Comment by RVL-Cubics** [comment]
> @kevinbasoftcat currently you cannot update that flag. We will update the module to help avoid this confusion in the future. I will be sure to share the feedback with the Partner Center team, that you would like for this field to be configurable. Please let me know if you have any other concerns or questions.

Why can we still not update this flag?

**Comment by mprentice22153** [comment]
Remember, this module was created for Legacy subscriptions. There was not an option to disable autorenew on Legacy but in special circumstances. Now with NCE we can disable auto-renew but this module was never designed to properly work with NCE. This module has been abandoned and is no longer supported. 

Your best option is to start using the Partner Center APIs. It will take some work to make the transition but you will be better off for it. I've improved my capabilities greatly by using the APIs. This API lets you update the auto-renew and other options on subscriptions.
https://learn.microsoft.com/en-us/partner-center/developer/update-a-subscription-by-id
