### ISSUE TITLE
Get-PartnerInvoiceStatement - Cannot access a closed Stream

### ISSUE THREAD

**Issue by cblackuk** [Microsoft/Partner-Center-PowerShell#117]
This used to work last month but no longer does.

I tested with old modules, new modules, and on three different computers. All return the same error for all invoices. So the command is basically broken at this point.

# Steps to reproduce
```powershell
$InvoiceId = Get-PartnerInvoice | Select-Object -Property InvoiceId -First 1
Get-PartnerInvoiceStatement -InvoiceId $InvoiceId.InvoiceId -OutputPath $Destination -Overwrite
```
## Expected behavior

Download of PDF

## Actual behavior
```powershell
$InvoiceId = Get-PartnerInvoice | Select-Object -Property InvoiceId -First 1
Get-PartnerInvoiceStatement -InvoiceId $InvoiceId.InvoiceId -OutputPath $Destination -Overwrite
Get-PartnerInvoiceStatement : Cannot access a closed Stream.
At line:1 char:1
+ Get-PartnerInvoiceStatement -InvoiceId $InvoiceId.InvoiceId -OutputPa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerInvoiceStatement], ObjectDisposedException
    + FullyQualifiedErrorId : System.ObjectDisposedException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerInvoiceStatement
```

Then it produces an empty pdf file with the name of the invoice...
## Module
```powershell
Get-Module -Name PartnerCenter

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.5.1904.2 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter...}

```

**Comment by cblackuk** [comment]
Update - the API works it is just the command.

# https://api.partnercenter.microsoft.com/v1/invoices/<invoice-id>/documents/statement

        # Declare API parameter
        ## Declare header for API call
        $HeaderAzureRm = @{
            Authorization = "Bearer $($AccessToken.AccessToken)"
        }

Invoke-WebRequest -Uri "https://api.partnercenter.microsoft.com/v1/invoices/<invoiceId>/documents/statement"  -Method Get -Headers $HeaderAzureRm -ContentType "application/json" -OutFile c:\temp\test13.pdf

**Comment by isaiahwilliams** [comment]
Hi @cblackuk, 

The required code changes have been merged, and this issue will be addressed in the next release. Right now I do not know the exact date when this release will be available through the PowerShell gallery. My hope is have it available before the end of the month.

**Comment by cblackuk** [comment]
Hi @isaiahwilliams,

Thank you ever so much for looking at it and fixing it so quickly! I can pull the invoice via API for this month and will re-test when you publish the fix in the next release.
Again, THANKS A LOT! I really appreciate such a rapid response and fixes :-)

**Comment by cblackuk** [comment]
Hi @isaiahwilliams, any news regarding the new module as the end of month is today and all my automation will fail...?

**Comment by cblackuk** [comment]
It works now! Thanks @isaiahwilliams!
