### ISSUE TITLE
Login-AzureRmAccount Without login prompt

### ISSUE THREAD

**Issue by mohammedzaid17** [microsoft/Partner-Center-PowerShell#119]
```
$Azusername='CSP Global Admin Username'
$Azpassword=convertto-securestring 'CSP Global Admin Password' -asplaintext -force
$cred=new-object -typename System.Management.Automation.PSCredential -argumentlist $Azusername,$Azpassword
$GetCred = Get-Credential $cred

Login-AzureRmAccount -Credential $GetCred
Select-AzureRmSubscription -TenantId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
$password = ConvertTo-SecureString "SomePass@123" -asplaintext -force
$azureAdApplication = New-AzureRmADApplication -DisplayName "MyApp" -HomePage "http://MyApp" -IdentifierUris "http://MyApp" -Password $password
$azureAdApplication
```

It is working till Select-AzureRmSubscription -TenantId  but shows error when executing New-AzureRmADApplication 
![image](https://user-images.githubusercontent.com/25500939/56120473-ca431e80-5f8b-11e9-8db3-a58767309a02.png)

Kindly help as i will be executing the above script from C#.
And I will be grateful if you help me find equivalent for above PowerShell snippet in C# since executing PowerShell script from C# is not good.
Thanks

**Comment by montereyharris** [comment]
Are you trying to create an Azure AD application in a customer tenant? Or is it your tenant?
If you are doing a customer tenant I believe you will need to set that when you do login-azurermaccount

Either way try set-azurermcontext rather than select-azurermsubscription

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mohammedzaid17** [comment]
> set-azurermcontext

Yes, I'm creating an Azure AD application in a customer tenant.
Above script is working fine but i need to enter username and password to execute New-AzureRmADApplication command.

Still its showing same error "_Azure credentials have not been set up or have expired_" when I try with set-azurermcontext.

But it works when executing 
```
Login-AzureRmAccount -Credential $GetCred
Select-AzureRmSubscription
```
Thank you for your response. Looking forward to hear from you.

**Comment by isaiahwilliams** [comment]
@mohammedzaid17 you need to specify the tenant identifier parameter when invoking the `Login-AzureRmAccount` command. It should look like 

```powershell
Login-AzureRmAccount -Credential $GetCred -TenantId $customerId
```

The value of the `$customerId` parameter is the identifier for the customer where you are connecting (e.g. 201726d7-1a9a-48b7-9b9d-fbc51cd7c041 or customer.onmicrosoft.com)

**Comment by isaiahwilliams** [comment]
Please let us know if you have any additional questions. If you need help with the Azure PowerShell module then I would recommend opening an issue [here](https://github.com/azure/azure-powershell/issues)
