### ISSUE TITLE
LastDirectorySyncTime empty

### ISSUE THREAD

**Issue by giarbi** [Microsoft/Partner-Center-PowerShell#12]
Get-PartnerCustomerUser returns no value for LastDirectorySyncTime

**Comment by isaiahwilliams** [comment]
Hi @giarbi, 

Can you confirm that the user in question is being synchronized using Azure AD Connect? If not that value should be empty.

**Comment by isaiahwilliams** [comment]
Hi @giarbi,

If you are still having an issue with this value being null for user that have been synchronized please re-open this request.

**Comment by johandehaan** [comment]
> Hi @giarbi,
> 
> Can you confirm that the user in question is being synchronized using Azure AD Connect? If not that value should be empty.

I've exactly the same issue. All of them have an empty LastDirectorySyncTime.

Also, is it possible to retrieve the immutableID of a user? This way I can find the corresponding AD User..
