### ISSUE TITLE
New-PartnerCustomerOrder throws "2004" error with Trial orders

### ISSUE THREAD

**Issue by jmeilleur1** [microsoft/Partner-Center-PowerShell#123]
$lineItems = New-Object -TypeName Microsoft.Store.PartnerCenter.PowerShell.Models.Orders.PSOrderLineItem
$lineItems.OfferId = "EB5BC29F-C744-4D36-8042-68BC11114EDA" (Tested several trials here with the same error)
$lineItems.Quantity = 25
New-PartnerCustomerOrder -CustomerId [insert customer id] -LineItems @($lineItems) 

Generates 
New-PartnerCustomerOrder : 2004 The following offer(s): EB5BC29F-C744-4D36-8042-68BC11114EDA does not support billing cycle type: Unknown

I see trials now need billingcycletype = "none" for trials
https://docs.microsoft.com/en-us/partner-center/develop/product-resources#billingcycletype 

I do not see any options in the cmdlet or the class that supports a billingcycletype parameter

Partner Center Module Version 1.5.1903.6
PS Version 5.1.14393.2879

**Comment by isaiahwilliams** [comment]
@jmeilleur1 you will be able to configure the billing cycle for orders with the next release. The required code changes have been made, and I hope to have everything ready to release early this week. Until that is available you can utilize the cart functionality instead.

**Comment by isaiahwilliams** [comment]
Hi @jmeilleur1 version 1.5.1905.1 was just released. Please update and you will find the billing cycle property now.
