### ISSUE TITLE
Unable to create token with refresh token

### ISSUE THREAD

**Issue by Agazoth** [microsoft/Partner-Center-PowerShell#128]
# Steps to reproduce
```ps
$SecretValue = "MySecretString"
$ClientAppId = "MyApplicationId"
$TenantID = "MyTenantId"
$Credential = New-Object System.Management.Automation.PSCredential ($ClientAppId, $SecretValue)
$token = New-PartnerAccessToken -Credential $credential -TenantId $TenantID
```

## Expected behavior

Token contains a refresh token

## Actual behavior

Token does not contain a refresh token

The guide found here: https://docs.microsoft.com/da-dk/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

states, that a token with a refresh token can be created by performing consent:
"When the command is invoked, you will be prompted to enter a username and password. Specify the application identifier as the username and the application secret as the password. When then New-PartnerAccessToken command is invoked, you will be prompted for credentials once again. This time you will need to specify the credentials for the service account that you will be using. The service account should be a partner account with the appropriate permissions. After the successful execution of the command, you will find that the $token variable contains the response from Azure Active Directory for a token. In the response is a refresh token, you will want to store this value in a secure repository such as Azure Key Vault or a similar service."

But it is unclear, what credentials should be used for the service account. 

It results in thei error when trying to authenticate with my Global Admin/AdminAgent account:
```ps
$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -TenantId $TenantID
New-PartnerAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
```

## Diagnostic logs

Will be shared if nessesary

## Environment

```ps
ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Binary     1.5.1904.3 PartnerCenter.NetCore               Core,Desk {Add-PartnerCustomerCartLineItem, Add-PartnerCusto…

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Agazoth** [comment]
Created a new refresh token in Windows Powershell 5.1 following the guide here: https://docs.microsoft.com/da-dk/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

Second authentication made with my GlobalAdmin/AdminAgent account.

Exported the refresh token to my key vault. Now this works:

```ps
$SecretValue = "Value from Key vault"
$ClientAppId = "Value from Key vault"
$TenantID = "Value from Key vault"
$refreshToken = "Value from Key vault"
$Credential = New-Object System.Management.Automation.PSCredential ($ClientAppId, $SecretValue)

$token = New-PartnerAccessToken -RefreshToken $refreshToken -TenantId $TenantID -Credential $Credential
Connect-PartnerCenter -AccessToken $token.AccessToken -ApplicationId $ClientAppId -TenantId $TenantID
```

Still cannot generate a token with a refreshtoken in PowerShell Core

**Comment by Agazoth** [comment]
It seems that the refresh token expires if not used in 90 days. Can anyone confirm this?

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

You are encountering this behavior because the device code flow is used with the PartnerCenter.NetCore module. This flow does not support web applications, so you will need to use a native application or the PartnerCenter module running on Windows to obtain the initial refresh token. I am currently exploring options to add support for web applications when using the PartnerCenter.NetCore 

Refresh tokens are only valid for 90 days even they are used. However, each time you make a request for a new token, Azure AD will return a new refresh token. You will want to update the refresh token you have stored at least once during the 90 day window.

**Comment by isaiahwilliams** [comment]
All updates regarding this topic will be posted on issue #100. Please use that issue if you have any additional concerns or questions.
