### ISSUE TITLE
New-PartnerCenterCustomerAgreement - Warning message

### ISSUE THREAD

**Issue by cblackuk** [microsoft/Partner-Center-PowerShell#131]
When we run the cmdlet in the latest module it displays this:
```powershell
WARNING: Breaking changes in the cmdlet 'New-PartnerCustomerAgreement' :
WARNING: - The API will now derive this value based on the authenticated user. So, this parameter will be removed in a future release.
WARNING: Note: The change is expected to take effect from the version '1.5.1906.1'
WARNING: NOTE : Go to https://aka.ms/partnercenterps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes with the Partner Center PowerShell module.
Customer: x.onmicrosoft.com has now agreed to the Microsoft Cloud Agreement
```

Which parameter will be removed in the next release as it appears to be broken Warning as it is just puts `-` there.
@isaiahwilliams - help please? We are using this cmdlet a lot so I would like to know what will break please :)

**Comment by isaiahwilliams** [comment]
I am not sure what is happening with the short link, but I will get that fixed. The user identifier parameter will be removed from that command.

Isaiah Williams
________________________________

**Comment by cblackuk** [comment]
@isaiahwilliams Thanks a lot for getting back to me so quickly. That makes perfect sense and it will not break anything for me :-) I hope ;-)

**Comment by isaiahwilliams** [comment]
If you have any issues please let us know. I am going to close this issue because there is not further action at this time.

**Comment by cblackuk** [comment]
Thanks @isaiahwilliams - did you manage to fix that warning in the end?
