### ISSUE TITLE
License Based Data (reconciliation) reoccuring

### ISSUE THREAD

**Issue by jf19742016** [microsoft/Partner-Center-PowerShell#132]
Within the portal you can download a usage or license based reconciliation file.  I understand that you can't automate via powershell downloading of the reconciliation file but you can do an export-csv.  How do you get the licence based recurring based data from powershell as Get-PartnerInvoiceLineItem doesn't return licence options?  It has billinglineitems and usagelineitems and neither of these contain licence based items e.g. "Azure Active Directory Premium P1"

**Comment by isaiahwilliams** [comment]
Hi @jf19742016, 

I did some testing this morning, and I would like to verify something with you. As part of my testing I ran the following command 

```powershell 
Get-PartnerInvoiceLineItem -BillingProvider Office -InvoiceId $invoiceId -LineItemType 'BillingLineItems'
```
The execution of the above command provide me a response similar to the following (note it has been truncated)
```
BillingCycleType                     : MONTHLY
BillingProvider                      : Office
ChargeEndDate                        : 5/25/2018 12:00:00 AM
ChargeStartDate                      : 4/26/2018 12:00:00 AM
ChargeType                           : CYCLE FEE
Currency                             : USD
CustomerId                           : 
CustomerName                         :
DomainName                           : 
DurableOfferId                       : 16C9F982-A827-4003-A88E-E75DF1927F27
InvoiceLineItemType                  : BillingLineItems
MpnId                                : 
OfferId                              : 
OfferName                            : AZURE ACTIVE DIRECTORY PREMIUM P1
OrderId                              : 
PartnerId                            : 
Quantity                             : 1
SubscriptionDescription              : AZURE ACTIVE DIRECTORY PREMIUM P1
SubscriptionEndDate                  : 2/26/2019 12:00:00 AM
SubscriptionId                       : 
SubscriptionName                     : AZURE ACTIVE DIRECTORY PREMIUM P1
```

When you run the command are you not seeing the OfferName property?

**Comment by jf19742016** [comment]
Thanks - I didn't expect it to be there.  Your Azure Active Directory licenses are under Office.... ;)
