### ISSUE TITLE
Hourly Granularity Does Not Return Any Result

### ISSUE THREAD

**Issue by lewislivingstone** [microsoft/Partner-Center-PowerShell#133]
Hi,

I am running the following command:
`Get-PartnerCustomerSubscriptionUtilization -CustomerId $customerId -SubscriptionId $subid -StartDate (Get-Date).AddDays(-5).ToUniversalTime() -Granularity Hourly -ShowDetails`

However, it does not return any results. Why is this?

Thank you
Lewis

**Comment by isaiahwilliams** [comment]
@lewislivingstone there are a number of reasons why this command will not return any information. Under most circumstances it is due to there being no information available for the defined period. Do you get information back for the same period when you run the command using the Daily granularity?

**Comment by lewislivingstone** [comment]
Hi Isaiah,

Yes, it returns Daily Granularity absolutely fine - that's why I was perplexed as I thought it might be because there was no data too.

Any other ideas?

Thanks
Lewis

**Comment by isaiahwilliams** [comment]
@lewislivingstone I did some testing on this a while back, and the Partner Center API was not returning data when the granularity was set to hourly. This is not expected when there is data available, so I would recommend that you open a support ticket. Since the issue is that the API is not returning information the Microsoft support organization should be able to help determine what is happening here.

**Comment by lewislivingstone** [comment]
Thanks @isaiahwilliams - I'll raise a Support case.

**Comment by lewislivingstone** [comment]
@isaiahwilliams - Hi Isiaiah, I have been working with Sonika at Microsoft Support and we have found that if we enter the date manually, then the Hourly command will work.

I.e. ` Get-PartnerCustomerSubscriptionUtilization -CustomerId $customerId -SubscriptionId $subid -StartDate 12/08/2019 -EndDate 14/08/2019 -Granularity Hourly -ShowDetails`

However, we cannot use `(Get-Date).AddDays(-4)` to enter the date within our command which means we cannot automate the pulling of this information (as we need to enter it manually).

Please can you advise if this is a bug or if you have a workaround for us to automate a previous day?

Thank you
Lewis

**Comment by lewislivingstone** [comment]
@isaiahwilliams I have managed to find a workaround by doing the following: `Get-PartnerCustomerSubscriptionUtilization -CustomerId $customerId -SubscriptionId $subid -StartDate (Get-Date).AddDays(-4).ToShortDateString() -EndDate (Get-Date) -Granularity Hourly -ShowDetails`

Not sure if this is a bug but this fixes my problem for now. Either bug needs fixing or the documentation needs updating.

**Comment by isaiahwilliams** [comment]
@lewislivingstone thank you for this update. I have updated the documentation for this command with the latest release. Please let me know if this [example](https://docs.microsoft.com/powershell/module/partnercenter/get-partnercustomersubscriptionutilization) provides you with the data you are seeking.

**Comment by isaiahwilliams** [comment]
Please let us know if you are still having issues with the latest release.
