### ISSUE TITLE
Unable to get Partner Center non AAD Roles via Powershell

### ISSUE THREAD

**Issue by SachinUpreti13** [microsoft/Partner-Center-PowerShell#138]
While trying to get the details of the admins present in the partner tenants I am facing issues while getting the details of the admins whose roles are not mentioned/present in AAD.  As show in picture we are able to get the group membership for the users with customers agent roles. But I need the command/way by which I can get the details of the account admin , MPN partner admin etc.  
![image](https://user-images.githubusercontent.com/52724805/61005324-a40ffd80-a385-11e9-8304-4589af18396f.png)
 

When we check out the partner center commands as in regards to the roles we only have below commands which does not fullfill the purpose:

Get-Command -Module PartnerCenter -Name "*ROLE*"
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-PartnerCustomerUserRoleMember                  1.5.1905.1 PartnerCenter
Cmdlet          Get-PartnerCustomerUserRole                        1.5.1905.1 PartnerCenter
Cmdlet          Remove-PartnerCustomerUserRoleMember               1.5.1905.1 PartnerCenter

There is no API call also which could help me .Please help me on this.

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 the Partner Center API does not return roles assigned at the partner level. The Partner Center roles are actually security groups in Azure AD. If you look at your tenant you will find the following groups

- AdminAgents
- HelpdeskAgent
- SalesAgent

You can use Microsoft Graph to obtain this information. I would recommend that you reference https://docs.microsoft.com/graph/api/group-list-members?view=graph-rest-1.0 for details on how to get this information.

**Comment by SachinUpreti13** [comment]
Hi Isaiah,

We did tested internally and found 2 API endpoints from Partner Center (not present in official documentation but generated them from spock).Below are the calls and attached 
![Capture](https://user-images.githubusercontent.com/52724805/61256955-8deeac80-a78c-11e9-9a0d-98c2b0a7db10.PNG)
 screenshots:

Roles : https://api.partnercenter.microsoft.com/v1/roles
Roles and Its members : https://api.partnercenter.microsoft.com/v1/roles/<ObjectID of the role>/usermembers 


Please advise if we can make changes to the module to get the roles and members.

**Comment by Paco2015** [comment]
I would like to support an idea of changes to the module to get powershell commands listing these roles and associated users. Now, MS is migrating MPN portal to ParnerCenter. If you are only MPN partner with many users, to list users / roles is impossible via Get-PartnerCustomerUserRole as you are not a customer, only MPN partner managed via PartnerCenter. so, this would help to many others in similar situation.

**Comment by isaiahwilliams** [comment]
The PartnerCustomerRole commands will only return directory role information for customers and not the partner. Additional features will need to be added to the SDK, to make this operation possible. The initial work to support this functionality has been completed. However, there is still some testing that needs to be performed and documentation developed. My hope is that we will be able to include this work in the next update.

**Comment by isaiahwilliams** [comment]
The ability to get these roles and list their members has been added to the [latest release](https://github.com/microsoft/Partner-Center-PowerShell/releases/tag/1.5.1908.1).
