### ISSUE TITLE
The supplied role does not have the rights to perform the requested operation

### ISSUE THREAD

**Issue by bilalAchahbar** [microsoft/Partner-Center-PowerShell#141]
Hello , 

I know that the same issue with the same title has been asked before in january this year. However there was no solution given to that person that"s why I will try it again.

I have set up an Azure AD application with a client ID and secret (the secret is not expired). some time ago but the script that I've run stopped working and stopped collecting data from the partner center and provides me the error message: The supplied role does not have the rights to perform the requested operation.

My script starts with the following: 

```
#Check if the CSP powershell module is installed, otherwise install it.
if (-not (Get-Module -Name "PartnerCenter")) {
  Install-PackageProvider Nuget –Force
  Install-Module -Name PartnerCenter -Confirm:$False -Force
}


$appId = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
$appSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxx' | ConvertTo-SecureString -AsPlainText -Force
$tenantId = 'xxxxxxxxxxxxxxxxxx'

#Perform this code if you want a new refreshtoken the token will be placed in the Csp folder in the txt file "Refreshtoken"
#$credential = New-Object System.Management.Automation.PSCredential $appId, $appSecret
#$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -TenantId $tenantId
#$token.RefreshToken  | Out-File #Check if the CSP powershell module is installed, otherwise install it.

#The refreshtoken was created by the Code above. Rerun the code above if you want to get a new token
$refreshToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 
# This will create a new accesstoken based on the refreshtoken so that the script will run automatically without any user interaction
$Newtoken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -ApplicationId $appId -ErrorVariable ExpiredToken
Connect-PartnerCenter -AccessToken $Newtoken.AccessToken -ApplicationId $appId  -TenantId $tenantId 

```

As you can see I've saved the refreshtoken and i will Get-Content the refreshtoken from the txt file and use it to login again with the partner center. This seems to be the new way of connecting to the partner center.

However by doing this I still get the same error message. Is there someone who also retrieved this error message. Is this some kind of bug? I have no clue what it means with the suplied role.

**Comment by isaiahwilliams** [comment]
@bilalAchahbar what operation are you trying to perform? The main reason yo will encounter this error is that you are attempting to perform an operation that requires Admin Agent privileges and the identity you are using does not have the role assigned.

**Comment by bilalAchahbar** [comment]
after the connection that doesn't work. I run this command `Get-PartnerCustomer´ to start my script where i fetch every customer and their billing hours per resource type. Now for you feedback over the admin agent is strange. It could be that someone in my organisation stripped the AD application from some admin roles. Can you guide me how to check what roles I need and where I can find the permissions of my Azure AD application. Because I didn't change my script (that runs every day for the past months) and somehow it stopped working with that error message.

**Comment by isaiahwilliams** [comment]
@bilalAchahbar you will need to check if the user, that was used to generate the refresh token, is still a member of the appropriate admin role in Partner Center. Usually the role used is the Admin Agents role because it can perform all operations the Partner Center API currently supports. You can check if the account has the appropriate rights by using the [user management](https://partner.microsoft.com/pcv/users) page in Partner Center.

**Comment by isaiahwilliams** [comment]
Please let us know if you are still having any issues.
