### ISSUE TITLE
No account or login hint was passed to the AcquireTokenSilent call

### ISSUE THREAD

**Issue by CStahlberg** [microsoft/Partner-Center-PowerShell#152]
# Steps to reproduce

`Connect-PartnerCenter`
`Get-PartnerAzureRateCard -Currency EUR -Region DE`

## Expected behavior
Should output the ratecard

## Actual behavior

`Get-PartnerAzureRateCard : No account or login hint was passed to the AcquireTokenSilent call.
In Zeile:1 Zeichen:1
+ Get-PartnerAzureRateCard -Currency EUR -Region DE
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerAzureRateCard], MsalUiRequiredException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalUiRequiredException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerAzureRateCard`
## Environment

Partner Center Version 2.0.1909.1
Powershell ISE was used

**Comment by isaiahwilliams** [comment]
@CStahlberg I have not been able to reproduce the issue you are encountering. Did you just run `Connect-PartnerCenter` without any parameters? Also, did you use an account associated with the Cloud Solution Provider program?

**Comment by CStahlberg** [comment]
@isaiahwilliams I ran it as it is shown above. The account I used is my CSP global admin and admin agent account. I tried to run the same script I run every day after having to modify it because parameter were changed to basic functions like `Connect-PartnerCenter`

**Comment by xyamasaki** [comment]
I was getting similar error message but updating the "PartnerCenter" module solved the problem (updated from v2.0.1909.3 to v2.0.1909.5).

When using v2.0.1909.3, running `Connect-PartnerCenter` without specifying a parameter failed with "MsalUiRequiredException" error message.

**Comment by isaiahwilliams** [comment]
@xyamasaki thank you for sharing this. There was a deployment issue that caused the wrong version of dependency to be included in the release build. That was corrected with the latest release. So, this issue should be completely resolved now. @CStahlberg if you are still having issues please let us know.
