### ISSUE TITLE
Get-PartnerCustomerSubscriptionUtilization Parameter Validation Error

### ISSUE THREAD

**Issue by CStahlberg** [Microsoft/Partner-Center-PowerShell#16]
# Steps to reproduce
Using Get-PartnerCustomerSubscriptionUtilization -CustomerId $customer.CustomerId -SubscriptionId $subscription.SubscriptionId -StartDate (Get-Date).AddMonths(-1).ToUniversalTime() -granularity Hourly -ShowDetails -EndDate (Get-Date).ToUniversalTime()
will give a validation error for end date because it is not a GUID.

## Expected behavior
Entering an end date should give me all usage data up to the date specfied.

## Actual behavior
I get a validation error stating:
Get-PartnerCustomerSubscriptionUtilization : Das Argument für den Parameter "EndDate" kann nicht überprüft werden. Das Argument "9/20/2018 12:00:00 AM +00:00" entspricht nicht dem Muster 
"^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$".

See:
https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/src/PowerShell/Commands/GetPartnerCustomerSubscriptionUtilization.cs

Why?
`/// <summary>
        /// Gets or sets the end date (in UTC) of the usages to filter.
        /// </summary>
        [Parameter(HelpMessage = "The end date (in UTC) of the usages to filter.", Mandatory = false)]
        [ValidatePattern(@"^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$", Options = RegexOptions.Compiled)]
public DateTimeOffset? EndDate { get; set; }`

**Comment by isaiahwilliams** [comment]
Hi @CStahlberg, 

I am not sure how that attribute got added to the end data parameter. This is a bug, and I will have a fix deployed for this issue by the end of the week. Please let us know if you discover any other issues.

**Comment by isaiahwilliams** [comment]
Hi @CStahlberg, 

I just published version 1.0.1809.8 which contains a fix for this issue. Thank you for opening the issue, please let us know if you have any other issues.
