### ISSUE TITLE
How to handle refresh-token has expired due to inactivity

### ISSUE THREAD

**Issue by thepill** [microsoft/Partner-Center-PowerShell#166]
# Steps to reproduce

Create a script without user interaction running longer than 90 days with a initial refresh-token set

## Expected behavior

The refresh-token gets updated automatically!?

## Actual behavior

The refresh token expires within 90 days
> The refresh token has expired due to inactivity. The token was issued on 2019-06-21T08:38:17.1046014Z and was inactive for 90.00:00:00.
## Question

I couldnt find any example on how-to refresh the token automatically within the 90 days - is there any? Or do i have to recreate a refresh-token every 90 days for a script wich is running without user-interaction?

Thanks!

**Comment by isaiahwilliams** [comment]
@thepill you are correct that, by default, a refresh token is only valid for 90 days. Each time you exchange a refresh token for an access token, a new refresh token is returned from Azure Active Directory. That refresh token is valid from the point in time it was generated plus 90 days. So, you can design a process that update the your stored refresh token, on a set interval (e.g. every 30 days) with a refresh token that is returned when you generate a new access token. 

I hope that this helps. Please let us know if you have any questions.

**Comment by thepill** [comment]
@isaiahwilliams Thank you!

I will give it a try and verify it in 90 days ;)

Will close this issue for now.
