### ISSUE TITLE
Connect-PartnerCenter 

### ISSUE THREAD

**Issue by prysmcorp** [microsoft/Partner-Center-PowerShell#168]
Receiving the following error when attempting to connect to partner center.

```powershell
PS C:\WINDOWS\system32> connect-partnercenter -accesstoken $token.AccessToken -applicationid $applicationid -Tenant $tenantid
Connect-PartnerCenter : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ connect-partnercenter -accesstoken $token.AccessToken -applicationid  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-PartnerCenter], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Store.PartnerCenter.PowerShell.Commands.ConnectPartnerCe
   nter```

**Comment by cblackuk** [comment]
```powershell
Connect-PartnerCenter -AccessToken $RefreshTokenForTesting.AccessToken 
```
As per new docs for AccessToken you just need to pass Access Token :-)

**Comment by prysmcorp** [comment]
That works. Perhaps the example listed further down that same page could be updated to reflect just the need for the access token? Ofc it also pulls those same examples with get-help

**Comment by isaiahwilliams** [comment]
I have updated the documentation in the repository, and I will make sure the changes get replicated to our documentation on docs.microsoft.com. Also, the updated example will be available through the `Get-Help` command with the next release. Thank you for letting us know about the issue.
