### ISSUE TITLE
Is there example on purchasing new Azure plan and creating subscriptions?

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#171]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Is there example on purchasing new Azure plan and creating subscriptions?
As this is coming next month and it is not even available in Sandbox to test we need to be prepared how we can implement this.

**Describe the solution you would like**
An example how this new azure plan is created and how subscriptions are created for that plan.

**Describe alternatives you have considered**

**Additional context**

**Comment by isaiahwilliams** [comment]
@slavizh since the official release of the new Azure experience in CSP was not until November 1, no examples could be generated. With the official release the module now support all of the API changes. To purchase an Azure plan you will leverage the cart operations. This is similar to how you purchase reserved instances. In the coming days we will be adding documentation that outlines how to do this through PowerShell.

**Comment by slavizh** [comment]
@isaiahwilliams what about subscription creation? As far as I understand that now goes trough Azure APIs. Does that means we have to wait for support from Az module? If that is the case who is making that work will be done in Az module?

**Comment by isaiahwilliams** [comment]
When you create an Azure Plan it will create one Azure subscription for you be default. Right now it is only possible to create additional subscriptions through the Azure portal or the ARM API.

Right now I am evaluating plans to add it to this module as well. However, this is not certain that this feature will be added. If the Az module will be adding it soon, then for sure I will not add it here.

I hope that this helps provide some insight into the planning that is happening.

Isaiah Williams

________________________________

**Comment by slavizh** [comment]
Ok. For now the current plan implementation makes it almost useless because creating one subscription and not having option to rename it, makes managing at scale impossible. Having subscriptions with the same name is deal breaker for us as well as  being able to create just one. I little bit disappointing that this was not available since day 1 like customer agreement signing.

**Comment by isaiahwilliams** [comment]
That definitely makes sense, and that is why I am considering adding that functionality here. Currently this module only interacts with the Partner Center API and Microsoft Graph. Adding the ability to interact with the ARM API is what we are considering, but I am trying to be careful not to overlap functionality between the Az and Partner Center module.

**Comment by isaiahwilliams** [comment]
@slavizh out of curiosity would you rather use on module for everything to manage the life cycle for a customer?

**Comment by slavizh** [comment]
I think I would prefer one module to avoid doing second authentication. This is of course we do not have to play a game of catchup where for example something is updated on Azure API (new feature may be) and Az implements it and on Partner Center we have to wait some time until we get it. Such could be the ability to set tags on subscriptions.

**Comment by isaiahwilliams** [comment]
@slavizh thank you for this feedback. Over the next several weeks a handful of commands will be added to provide support of the Azure Plan scenarios in the context of a partner.

**Comment by o-l-a-v** [comment]
Status on this, can we add subscriptions to Azure Plan using Partner Center module now? Or using Az?

**Comment by slavizh** [comment]
You can. Check the latest module.

**Comment by o-l-a-v** [comment]
> You can. Check the latest module.

I've checked documentation, Get-Command, googled, but can't find any obvious way of adding subs to azure plan with Partner Center module. Could you or anyone else provide a hint?

**Comment by o-l-a-v** [comment]
Made it happen with REST code provided by Wesley Haakman

* https://www.wesleyhaakman.org/creating-customer-subscriptions-under-an-azure-plan-using-the-rest-api/

**Comment by slavizh** [comment]
No need for rest:
https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partnerazuresubscription?view=partnercenterps-3.0
Azure plan is created by the order cmdlets. When the first Azure plan is created it will create also one azure plan subscription with default name which can be changed with https://docs.microsoft.com/en-us/powershell/module/partnercenter/set-partnerazuresubscription?view=partnercenterps-3.0

**Comment by o-l-a-v** [comment]
For people who needs an example for how to add Azure subscriptions to customers with Azure Plan

```powershell
# Add Azure Subscription to CSP customer with Azure Plan
## Assets
$AzureTenantGUID  = ''
$SubscriptionName = '' 

# PowerShell Preferences
$ErrorActionPreference = 'Stop'

# Connect PartnerCenter - Should open up a browser
if (-not[bool]$(Try{$null=Get-PartnerBillingProfile;$?}Catch{$false})){Connect-PartnerCenter}

# Get billing account for Azure Plan / Microsoft Customer Agreement
$BillingAccount = $(Get-PartnerAzureBillingAccount).Where{$_.'AgreementType' -eq 'MicrosoftCustomerAgreement'}

# Get customer by Tenant GUID
$Customer = Get-PartnerCustomer -CustomerId $AzureTenantGUID

# Add Azure Subscription
if ((-not[string]::IsNullOrEmpty($Customer.'CustomerId')) -and $Customer.'CustomerId' -eq $AzureTenantGUID) {
    New-PartnerAzureSubscription -BillingAccountName $BillingAccount.'Name' -CustomerId $Customer.'CustomerId' -DisplayName $SubscriptionName
}

# Disconnect PartnerCenter
Disconnect-PartnerCenter
```
