### ISSUE TITLE
Get customDomains with Get-PartnerCustomer

### ISSUE THREAD

**Issue by Mogge66** [microsoft/Partner-Center-PowerShell#172]
Why can't i retreive customDomains with Get-PartnerCustomer?
If i run this...
Get-PartnerCustomer -CustomerId 'xxxxxxxx-b209-4b18-847a-497405535b02' | Select-Object *
.. i only gets these properties:

AllowDelegatedAccess  : True
AssociatedPartnerId   : 
BillingProfile        : 
CommerceId            : 
CustomerId            : xxxxxxxx-b209-4b18-847a-497405535b02
Domain                : customer.onmicrosoft.com
Name                  : Sample Customer
RelationshipToPartner : Reseller

Is it possible to get all of a customers custom domains?

**Comment by isaiahwilliams** [comment]
@Mogge66 this module is using the Partner Center API to get customer information. Unfortunately the data returned from that API does not include any custom domains. I am currently exploring the various options for delivering this type of feature. As progress is made I will be updating #40. Thank you for providing this request.
