### ISSUE TITLE
Set-PartnerCustomer cmdlet doesn't use input parameters

### ISSUE THREAD

**Issue by mattheuslee** [Microsoft/Partner-Center-PowerShell#18]
## Expected behavior

Set-PartnerCustomer should update the customer billing profile using the given input parameters if they are non-null and valid.

## Actual behavior

Set-PartnerCustomer doesn't seem to use the input parameters in updating the customer billing profile for many of the billing profile properties. Instead it is currently using `Name`, which results in an invalid data error being produced.

For example, line 129 of src/PowerShell/Commands/SetPartnerCustomer.cs is currently:
`customer.BillingProfile.DefaultAddress.AddressLine1 = UpdateValue(Name, customer.BillingProfile.DefaultAddress.AddressLine1);`

When it probably should be:

`customer.BillingProfile.DefaultAddress.AddressLine1 = UpdateValue(BillingAddressLine1, customer.BillingProfile.DefaultAddress.AddressLine1);`

Same comment applies to lines 130-136.

## Environment

Using PartnerCenter V1.0.1809.6 from the PowerShell Gallery

**Comment by isaiahwilliams** [comment]
Hi @mattheuslee, 

I have corrected this issue and will be deploying an updated version to the PowerShell gallery later this week. Please let us know if you discover any other issues.

**Comment by mattheuslee** [comment]
Thanks for the update, I'm looking forward to using the updated module.

**Comment by isaiahwilliams** [comment]
Hi @mattheuslee, 

I just merged PR #20 that included a fix for this issue. Also, version [1.0.1809.10](https://www.powershellgallery.com/packages/PartnerCenter/1.0.1809.10) is now available through the PowerShell gallery. Please let us know if you discover any other issues.
