### ISSUE TITLE
Unable to connect to the partner center powershell module via secure application method

### ISSUE THREAD

**Issue by SachinUpreti13** [microsoft/Partner-Center-PowerShell#180]
i am trying to connect to the partner center powershell module v2.0, below are the set of commands which I am using for the connection :

$cred=Get-Credential
$appid="<application ID>"
$tenant="<Tenantid>"
New-PartnerAccessToken -ApplicationId $appid -Credential $cred -Scopes "https://api.partnercenter.microsoft.com/user_impersonation" -ServicePrincipal -Tenant $tenant -UseAuthorizationCode

Below is the error which I receive. 
![Capture](https://user-images.githubusercontent.com/52724805/68072303-4e36e980-fdaa-11e9-821f-ba7564bde22b.PNG)

The redirect URI which i have set is https://localhost/

and the article used for reference is https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 when using the `UseAuthorizationCode` parameter you will be prompted to authentication interactively using the authorization code flow. The redirect URI value will be generated dynamically. The generation process will attempt to find a port between 8400 and 8999 that is not in use. Once an available port has been found, the redirect URL value will be constructed (e.g. http://localhost:8400). So, it is important that you have configured the redirect URI value for your Azure Active Directory application accordingly.

**Comment by SachinUpreti13** [comment]
if we are using our marketplace then how that should be the redirect URL for eg my marketplace address is www.abc.com. Then how should I use it in the application.

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 I am not sure that I follow what you are asking. Would it be possible for you to provide an example?

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 if you are still having issues please let me know.
