### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0.....

### ISSUE THREAD

**Issue by desireewilliams** [microsoft/Partner-Center-PowerShell#181]
With the release of version 2.0.1911.1, I updated my existing module in order to get some of the newer cmdlets that were released. Connect-PartnerCenter still works (well, sort of. The -ApplicationId option is no longer valid, but I could get it to connect so that's neither here nor there).

However, when I run any other command I get:
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Get-PartnerCustomer
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomer], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomer

The two cmdlets that I tested this on are Get-PartnerCustomer and Get-PartnerCustomerUsageRecord. I have also replicated the behavior on a system that has never had the PartnerCenter module installed on it.

If I open the folder with the module files in it, there is a Newtonsoft.Json.dll available. However, it is not the version mentioned above:
![image](https://user-images.githubusercontent.com/57154883/68343389-e9310b80-00a9-11ea-971a-ca3a1bd5574e.png)

**Comment by isaiahwilliams** [comment]
@desireewilliams would it be possible for you to share the output from `Get-Module` after you have loaded all the modules had loaded when you encountered this error?

**Comment by desireewilliams** [comment]
@isaiahwilliams here is both the error and the modules from a new instance of PowerShell
![image](https://user-images.githubusercontent.com/57154883/68402076-feed1200-0137-11ea-9de4-d555c025972a.png)

Here's a text version of the Get-Module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-Auth...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSMan...
Script     2.0.1911.1 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember,...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKe...

**Comment by Sam09m** [comment]
I'm experiencing a similar issue. I'm able to Connect to Partner Center, but not perform a Get-PartnerUser command. Screenshot attached:
![image](https://user-images.githubusercontent.com/54146802/68429073-08e03680-0173-11ea-8b27-7a3b992723a7.png)

**Comment by isaiahwilliams** [comment]
@desireewilliams and @Sam09m  thank you for opening this issue. I just released version [2.0.1911.2](https://www.powershellgallery.com/packages/PartnerCenter/2.0.1911.2) which contains a fix for this issue. After updating to the latest version please let me know if you have any other issues.
