### ISSUE TITLE
Get-PartnerCustomerLicenseDeploymentInfo throws Microsoft.Store.PartnerCenter.Exceptions.PartnerException

### ISSUE THREAD

**Issue by gahujipo** [microsoft/Partner-Center-PowerShell#182]
# Steps to reproduce

```powershell
$Password = $Secret  | ConvertTo-SecureString -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential $ApplicationId, $Password
$PartnerCenterSession = Connect-PartnerCenter -Credential $Credential -Tenant $TenantId -ServicePrincipal
$sourceTenant = Get-PartnerCustomer -CustomerId “xxxx”
$deployedSubscriptions = Get-PartnerCustomerLicenseDeploymentInfo -CustomerId $sourceTenant.CustomerId
```

## Expected behavior

Should output **Microsoft.Store.PartnerCenter.PowerShell.Models.Analytics.PSCustomerLicensesDeploymentInsights** like specified in [docs](https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnercustomerlicensedeploymentinfo?view=partnercenterps-2.0).

## Actual behavior

![image](https://user-images.githubusercontent.com/26710574/68405189-f0c2e400-017f-11ea-96f6-dc9661aded4b.png)

## Diagnostic logs

PartnerCenter Module Version: 
![image](https://user-images.githubusercontent.com/26710574/68405220-fae4e280-017f-11ea-9746-64fc9cae11df.png)

## Environment

Version 2.0.1909.5
Windows 1903
PowerShell 5.1

**Comment by gahujipo** [comment]
The credentials I am using are service principal credentials of a reseller.

**Comment by isaiahwilliams** [comment]
@gahujipo - You are encountering this error because this operation requires app + user authentication. So, you will not be able to authenticate using a service principal for this operation. You can find more information on this [here](https://docs.microsoft.com/partner-center/develop/get-licenses-deployment-information)
