### ISSUE TITLE
Get-PartnerCustomer: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by defoortd** [microsoft/Partner-Center-PowerShell#183]
# Steps to reproduce

After import of the module and connecting to PartnerCenter i wanted to get a list of all customers and i keep getting this error. 

## Expected behavior

Get list of customers

## Actual behavior

![image](https://user-images.githubusercontent.com/49642760/68487232-00efc780-0243-11ea-8474-2f4b9846112b.png)

## Environment

PartnerCenter version 2.0.1911.1

**Comment by isaiahwilliams** [comment]
@defoortd thank you for opening this issue. I just released version [2.0.1911.2](https://www.powershellgallery.com/packages/PartnerCenter/2.0.1911.2) which contains a fix for this issue. After updating to the latest version please let me know if you have any other issues.
