### ISSUE TITLE
Generating RefreshToken for Exchange online fails

### ISSUE THREAD

**Issue by KelvinTegelaar** [microsoft/Partner-Center-PowerShell#186]
When using the documentation at https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0#exchange-online-powershell%C2%A0

Generating a refresh token for Delegated Exchange administration fails. 

Code executed:
`
$token = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant 'MYTenantID' -UseDeviceAuthentication
`

Error:
```

new-PartnerAccessToken : Object reference not set to an instance of an object.
At line:1 char:10
+ $token = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken
```

**Comment by KelvinTegelaar** [comment]
When using the "old method" of authentication we get an error that the reply URL is incorrect, which is expected behaviour.

**Comment by isaiahwilliams** [comment]
@KelvinTegelaar version [2.0.1911.3](https://www.powershellgallery.com/packages/PartnerCenter/2.0.1911.3) has just been released and included a solution for this issue. Please update to the latest version and let us know if you have any further issues.
