### ISSUE TITLE
Issues with PartnerSignInActivity

### ISSUE THREAD

**Issue by kevinbasoftcat** [microsoft/Partner-Center-PowerShell#191]
# Steps to reproduce
https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnerusersigninactivity?view=partnercenterps-2.0

> What steps can reproduce the defect?
Using version .1 of the module only works in PowerShell Core 6.0. If we get all partner users as per the above article it returns over 4000 in our tenant. When running tjhe second command to get sing in activities it errors after a few hours.

Using version .2 or .3 of the module the Get-PartnerUser command only ever returns 100 users.

> Please share the setup, commandline for vstest.console, sample project, target

> framework etc.

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by isaiahwilliams** [comment]
This issue will be resolved with the next release. All of the code changes have been made, and we are targeting the end of this week for the release. I will update this issue when everything has been pushed to the PowerShell gallery.

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kevinbasoftcat** [comment]
Hi Isaiah,

Thank you for the update I will await your feedback.

Thanks,
Kevin Barlow

**Comment by isaiahwilliams** [comment]
@kevinbasoftcat I have just released version [2.0.1911.4](https://www.powershellgallery.com/packages/PartnerCenter/2.0.1911.4) that contains a hotfix for this issue. After you update all user accounts will be returned. Please let us know if there are any other issues.

**Comment by kevinbasoftcat** [comment]
Thanks Isaiah,

I will test this now.
