### ISSUE TITLE
Get-AzureADUser does not work with delegated tokens

### ISSUE THREAD

**Issue by gavsto** [microsoft/Partner-Center-PowerShell#192]
# Steps to reproduce

> What steps can reproduce the defect?
`Connect-AzureAD -AadAccessToken $aadGraphToken.AccessToken -MsAccessToken $graphToken.AccessToken -TenantId $TenantIdClient -AccountId "$MyGlobalAdminUPN"`

then 

`Get-AzureADUser`

> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

PartnerCenter Module 2.0.1911.3
AzureAD Module 2.0.2.61

## Expected behavior
A list of users is returned from the tenant

## Actual behavior
Errors out:
`Get-AzureADUser : Error occurred while executing GetUsers 
Code: Request_BadRequest
Message: Invalid domain name in the request url.
RequestId: 5f2e7d7b-b5a6-44fa-b7eb-04e1ba0eae68
DateTimeStamp: Tue, 19 Nov 2019 16:56:19 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

At line:1 char:1
+ Get-AzureADUser -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser`

There seems to be a number of people with the same issue here https://www.microsoftpartnercommunity.com/t5/Secure-Application-Model/Connect-AzureAD-to-Other-Tenants-with-Secure-Application-Model/m-p/13767

**Comment by isaiahwilliams** [comment]
@gavsto can you share details on how you generated the access tokens being used?

**Comment by isaiahwilliams** [comment]
@gavsto can you share the details on how you generated the tokens and we will be glad to help?

**Comment by isaiahwilliams** [comment]
@gavsto I would recommend that you review the steps documented [here](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0). They will guide you through generating the appropriate access token for Azure AD PowerShell. If you are still having issues please feel free to re-open this issue.
