### ISSUE TITLE
Why New-PartnerAzureSubscription requires CustomerName parameter

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#203]
# Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I am always frustrated when [...]

Why New-PartnerAzureSubscription requires CustomerName parameter. Customer name is not unique property. It should require tenantid/customerId otherwise if there are two customers with the same name problems will occur.

**Describe the solution you would like**

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**

**Comment by isaiahwilliams** [comment]
@slavizh this particular command is calling the Azure Resource Manager API to create the subscription. That parameter is one of the required values for how the API was designed. It might be possible to interchange the identifier and name, but I have only tired using the customer name. 

You can find more details about the API [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/programmatically-create-subscription?tabs=rest#create-subscriptions-for-an-mpa-billing-account).

**Comment by slavizh** [comment]
@isaiahwilliams is it possible that you change the command in a way that we provide customer ID and the commandlet finds the customer and provides the needed information to the API. That would be better and more consistent experience within the whole module

**Comment by isaiahwilliams** [comment]
@slavizh with the release of version 3.0 we will be adding the `CustomerId` parameter to this command. Also, the currently plan is to remove the `CustomerName` parameter when version 3.0.1 is released.

**Comment by isaiahwilliams** [comment]
@slavizh version 3.0 has been released. You can find the details regarding the release [here](https://docs.microsoft.com/en-us/powershell/partnercenter/release-notes?view=partnercenterps-3.0). Thank you for sharing this feedback it is greatly appreciated.
