### ISSUE TITLE
Connect-PartnerCenter with client secret

### ISSUE THREAD

**Issue by Agazoth** [Microsoft/Partner-Center-PowerShell#21]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Log on in scripts is not possible in a tenant with MFA

**Describe the solution you would like**
With the depricated Add-PCAuthentication you could log on with a application id and client secret. Could that option be integrated in the new Connect-PartnerCenter?

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, this is a feature that we hope to have available later this month. Most of the work for this change has been completed, but we still need to do regression testing and a security review. I will keep you posted on our progress with this change.

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

I have just published version [1.5.1810.2](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1810.2). With this update I have added support for app only authentication. You can now connect using the following 

```powershell
$credential = Get-Credential
Connect-PartnerCenter -Credential $credential -ServicePrincipal -TenantId 64a764b0-3cda-4311-88ff-9e00aeb02dec
```

The username portion of the credentials needs to be the application identifier and the password portion needs to be the application secret. Please note that some parts of the Partner Center API require app + user authentication, so this means you will not be able to perform those operations using this new authentication method. Please let me know if you have any concerns or questions.

**Comment by Agazoth** [comment]
Thanks Isaiah, I will give it a spin tomorrow.

**Comment by Agazoth** [comment]
I think I ran into a full stop. I'm trying to automate billing, and the only thing I cannot get is the Billing Profile of the customer. I think it is caused by the authentication method. Can you confirm, that Get-PartnerCustomerBillingProfile is one of the cmdlets that cannot be used with this authentication method?

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

According to the documentation it supports both authentication models. However, through some testing it appears to only support app + user authentication. Are you receiving an error similar to the following? 

Get-PartnerCustomerBillingProfile : The supplied role does not have the rights to perform the requested operation.

I am going to do some additional testing to validate this.

**Comment by Agazoth** [comment]
Yes, that is exactly the error I receive.
