### ISSUE TITLE
Ability to Suspend Activate Azure Plan subscriptions

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#212]
# Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I am always frustrated when [...]
Please provide option to set the status of Azure Plan subscription. This option is available for CSP subscriptions. Provide it in Set-PartnerAzureSubscription cmdlet.

**Describe the solution you would like**

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**

**Comment by isaiahwilliams** [comment]
@slavizh based on my understanding the ability to suspend Azure subscriptions under an Azure Plan through an API is not available yet, but the cancel functionality is available. This is definitely something that we would like add but we will need to wait until the API is available.

**Comment by slavizh** [comment]
@isaiahwilliams it is possible from Azure Portal if you browse the customer though. May be the customer should not be allowed to cancel subscription to mimic the behavior with CSP offer and this should be partner operation only.

**Comment by isaiahwilliams** [comment]
This functionality has been added with a recent release. Thank you for opening this feedback request.
