### ISSUE TITLE
Ability to enable/disable Azure Cost Management for customers onboarded to Azure Plan

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#213]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Provide option to enable/disable Azure Cost Management for customers that are onboarded to Azure Plan.

**Describe the solution you would like**

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**

**Comment by isaiahwilliams** [comment]
@slavizh thank you for this feedback. This is definitely is something that should be added, to ensure partners can opertionalize all of the new features.

If you would like to contribute that will help us deliver this feature more quickly. Please feel to contribute to the development of this module.

**Comment by isaiahwilliams** [comment]
@slavizh with version 3.0 this functionality has been added. You can find documentation on how to configure the policy [here](https://docs.microsoft.com/en-us/powershell/module/partnercenter/set-partnerazurebillingpolicy?view=partnercenterps-3.0). Thank you for providing this request!

**Comment by slavizh** [comment]
Thank you! Did a test and it works.
