### ISSUE TITLE
New-PartnerAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

### ISSUE THREAD

**Issue by rodrijp** [microsoft/Partner-Center-PowerShell#214]
We're doing the steps related with [Enabling secure application model on CSP in order to use powershell.](https://docs.microsoft.com/es-es/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5)

We use the last libraries, net framework 4.8 and PS 5.1,
We call _New-PartnerAccessToken_ in order to get the consent. 

> $token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -TenantId $tenantId

But the result was an error:

> WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CGK5CS256 to authenticate.
> New-PartnerAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
> Trace ID: 9bd9eff5-cfb4-41a2-bd7f-34e23eb7a400
> Correlation ID: 337c86bd-887d-4aaa-85f5-e3e77dadf5db
> Timestamp: 2019-11-28 17:06:39Z
> At line:1 char:10
> + $token = New-PartnerAccessToken -Consent -Credential $credential -Res ...
> +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], AuthenticationException
>     + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.AuthenticationException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken

![NewPartnerAccessTokenConsent](https://user-images.githubusercontent.com/1482508/69821893-2c901d00-1205-11ea-9f90-994b5d926138.png)

Any idea, Why do we have this result?
Thanks
Rodrigo

**Comment by isaiahwilliams** [comment]
@rodrijp can you uninstall the PartnerCenter.NetCore module and try again?

That module does work with PowerShell 5.1 it is only meant for PowerShell Core. Newer versions of the PartnerCenter module work on both versions of PowerShell.

**Comment by rodrijp** [comment]
Hi @isaiahwilliams,

I uninstall PartnerCenter.NetCore module. 
But then we found the library dosen't have the method _New-partnerAccesToken_ with _consent_ flag. 

I only found the correct method signature on PartnerCenter.NetCore.

![image](https://user-images.githubusercontent.com/1482508/70144704-cd1b8c80-169e-11ea-8f90-2b26430f138b.png)

Thanks 
Rodrigo

**Comment by isaiahwilliams** [comment]
Hi @rodrijp, 

Starting with the 2.0 release the parameters for that command have changed. If you are planning to use the latest version of the PartnerCenter module, then I would recommend following the steps documented [here](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0)

**Comment by rodrijp** [comment]
Thanks @isaiahwilliams 

Very helpful, I read the previous release documentation.  :-( Now I understand the issue.

Have a nice day. 
Rodrigo

**Comment by isaiahwilliams** [comment]
@rodrijp glad to hear that it is working for you now!
