### ISSUE TITLE
Remove-PartnerSandboxCustomer does not work when Azure Plan is purchased

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#215]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

The command returns error:

```
Remove-PartnerSandboxCustomer : Customer relationship cannot be removed due to active Azure reserved instances.Please cancel the following orders: 0bed3bbca6c
```

That customer does not have reserved instances purchased. It has Azure plan purchased only and the order id is for Azure Plan purchase. Did the functionality to remove customers in Sandbox is deprecated when using Azure Plans or this is bug?

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by slavizh** [comment]
Nowhere documented but subscriptions needs to be cancelled and than Azure plan suspended.

**Comment by isaiahwilliams** [comment]
@slavizh thank you for sharing this information. If I remember correctly you have opened an issue on the Partner Center documentation about this. I will share this information with them, and ask that they add details regarding the suspension in the documentation for Partner Center. That way everyone will be able to find it. I really appreciate you sharing the details!
