### ISSUE TITLE
unable to connect to the Exchange Online PowerShell via Service Principal 

### ISSUE THREAD

**Issue by SachinUpreti13** [microsoft/Partner-Center-PowerShell#229]
I am trying to connect to the Exchange Online PS via my partner credentials. I am able to get the token successfully via admin credentials but when using service principal I get the below error. We are using the same application as I have used in both the cases there has been no changes in this. Attached is the screenshot for your reference.

New-PartnerAccessToken : AADSTS7000215: Invalid client secret is provided.
Trace ID: 3121f455-760a-4a0a-af2f-a7958bfe3f00
Correlation ID: 6f521f13-c71f-4e47-a767-3a88a7e06e13
Timestamp: 2019-12-12 14:51:38Z
At line:1 char:1
+ New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalServiceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken

I am using  2.0.1909.5 version of Partner center module

PS C:\WINDOWS\system32> Get-Module -Name PartnerCenter

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.1909.5 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter...}
![Capture](https://user-images.githubusercontent.com/52724805/70723109-5f1a3980-1d1e-11ea-96c5-93b10f96cc54.PNG)

====================================================

Adding to the above the powershell 3.0 documentation states to generate the initial refresh token via below command :

$token = New-PartnerAccessToken -Module ExchangeOnline

but i am not able to get the -Module parameter while trying to execute above command

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 please update to version 3.0 of the module and follow the guidance available at https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0#exchange-online-powershell

**Comment by SachinUpreti13** [comment]
@isaiahwilliams Thanks for that update. I was able to update my module and tried to connect using the document provided above. But there is an error while creating a new session. we have DAP active with the end customers tenant but still the access denied message comes up.
![Capture](https://user-images.githubusercontent.com/52724805/70736994-934e2400-1d37-11ea-92a8-cd4e9f0406b8.PNG)


Any suggestions?

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 when you generated the refresh token did you use an account that has Admin Agent privileges? If you did can you confirm that account can be used to access the EAC?

**Comment by SachinUpreti13** [comment]
@isaiahwilliams  yes the account i have using have access to admin agent in the partner center portal. I have a query in regards to the script in the above documentation. $customerId represents the tenant id of the customer whose tenant we are trying to access ?

**Comment by SachinUpreti13** [comment]
@isaiahwilliams Hi could you please advise on this issue ?

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 can you confirm that the EAC loads as expected when utilizing that account? I am trying to rule out an issue with the relationship that is impacting Exchange.

**Comment by isaiahwilliams** [comment]
@SachinUpreti13 since this is not an issue with the module I would recommend working with Microsoft support or the community through the [Microsoft Partner Community](https://www.microsoftpartnercommunity.com/t5/Partner-Center-Security-Guidance/ct-p/partner-center-security-guidance). Please let us know if you have any issues with the module and we will be glad to help.
