### ISSUE TITLE
[Feature Request] Ability to change PartnerID on subscriptions

### ISSUE THREAD

**Issue by gutyex** [microsoft/Partner-Center-PowerShell#235]
Get-PartnerCustomerSubscription returns the property 'PartnerId', but there is no way to change this using Set-PartnerCustomerSubscription

**Comment by isaiahwilliams** [comment]
@gutyex thank you for opening this feature request. The require code changes for this feature have been made. However, due to the holidays there will not be another release of the module this year. This functionality will be made generally available after the first of the year.

**Comment by isaiahwilliams** [comment]
@gutyex I decided to release the next version early to help unblock a handful of scenarios. Starting with version [3.0.3](https://www.powershellgallery.com/packages/PartnerCenter/3.0.3) this functionality has been added. Please let us know if there is anything else missing that you might need.
