### ISSUE TITLE
Exchange online powershell - Unable to get refresh token programatically and via a site

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#240]
# Steps to reproduce

With all of the secure application models, we can have this trigger via a URL to grant consent and return a refreshtoken.
However this does not seem possible for exchange online and it is critical that we can collect this.

$token = New-PartnerAccessToken -Module ExchangeOnline
It requests going to a site and entering in the code
Its a bit more hands on than the current methods where we can use a URL to grant access to the application and then return that output to a url.

How can we capture the refreshtoken from the process to use in our application?

https://docs.microsoft.com/en-gb/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0

I am hoping there is just something I have missed and there is an easy way to achieve this.

## Expected behavior

Have a way for a user to click a link and grant access to the module so we can capture the refresh code.

## Actual behavior

Seems this is currently manual and we need to be able to programatically collect this.

## Diagnostic logs

With all of the other partner center secure application model, we have a url to click with our application id which a user can grant consent and it returns a refresh token to the website.
How can we achieve the same outcome with exchange online?

It appears that the only way to do it is to have someone manually run the commands in powershell and then provide us the refresh token. Please assist.

## Environment

Partner Center powershell 3.0.2

**Comment by isaiahwilliams** [comment]
@Shadoxity that particular command is how you generate the initial refresh token. That value should be stored somewhere secure like Azure Key Vault. After you generate that value you will use the following to get an access token using the securely stored refresh token

```powershell
$customerId = '<CustomerId>'
$refreshToken = '<RefreshTokenValue>'
$upn = '<UPN-used-to-generate-the-refresh-token>'

$token = New-PartnerAccessToken -Module ExchangeOnline -RefreshToken $token.RefreshToken -Tenant $customerId

$tokenValue = ConvertTo-SecureString "Bearer $($token.AccessToken)" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)

$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid?DelegatedOrg=$($customerId)&BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection

Import-PSSession $session
```

**Comment by Shadoxity** [comment]
Hey @isaiahwilliams  That is my point,
The problem is generating the initial refresh token without having someone manually go into powershell and create it and then copy and paste it somewhere.

For the other partnercenter methods we can use the URL for our azure application to grant consent. How can we do a similar thing for exchange? I need to be able to programatically grant the consent and get the refresh token.

Please assist.
