### ISSUE TITLE
New Azure plan for CSP partner and Powershell script

### ISSUE THREAD

**Issue by bwalton140** [microsoft/Partner-Center-PowerShell#248]
I have a script we use for onboarding customers. Once the new CSP Azure plan was added the script no longer see the subscriptions under the Azure plan. I update module to 3.0.2
Get-PartnerCustomerSubscription
When I run that command it only shows the Azure plan subscription not the other subscription under the Azure plan. see example attachments
![partner center Azure plan](https://user-images.githubusercontent.com/47036845/71586818-77919e80-2ae9-11ea-8944-a2bad9b2395f.png)
[git hub request stepstone.xlsx](https://github.com/microsoft/Partner-Center-PowerShell/files/4010067/git.hub.request.stepstone.xlsx)

**Comment by isaiahwilliams** [comment]
@bwalton140 with the Azure Plan this is the expected behavior. You will need to get the entitlements to get the identifiers for the subscriptions. See the following for more information on how to do this
https://docs.microsoft.com/powershell/module/partnercenter/get-partnercustomerazureplanentitlement

**Comment by bwalton140** [comment]
Isaiah that was very helpful I still have a problem. I will not create the reader role in the subscription
New-AzRoleAssignment -ObjectId $SPO.ObjectId  -RoleDefinitionName Reader -Scope "/subscriptions/$($SubId.Id)"
I do not get a error but when I check the subscription role it is not there.
[test AJH Azure Test Customer 20190322.txt](https://github.com/microsoft/Partner-Center-PowerShell/files/4019613/test.AJH.Azure.Test.Customer.20190322.txt)



[Azureplan1 github.txt](https://github.com/microsoft/Partner-Center-PowerShell/files/4019619/Azureplan1.github.txt)
I get everything in my csv file ok
