### ISSUE TITLE
Can't get customers who have agreed to Customer Agreements

### ISSUE THREAD

**Issue by jaehungim31** [microsoft/Partner-Center-PowerShell#253]
# Steps to reproduce
```powershell
Connect-PartnerCenter
# New Customer Agreement
New-PartnerCustomerAgreement -CustomerId "<Customer's ID>" -AgreementType "MicrosoftCustomerAgreement" -ContactEmail "<Customer's Email>" -ContactFirstName "<Customer's FirstName>" -ContactLastName "<Customer's LastName>" -ContactPhoneNumber "<Customer's PhoneNumber>" -TemplateId "117a77b0-9360-443b-8795-c6dedc750cf9"
```

## Expected behavior
```PowerShell
Get-PartnerCustomerAgreement -CustomerId "<Customer's ID>"
# Display CloudAgreement & CustomerAgreement
```

## Actual behavior
```PowerShell
Get-PartnerCustomerAgreement -CustomerId "<Customer's ID>"
# Only showing CloudAgreement
```
![image](https://user-images.githubusercontent.com/16345479/72050288-1c8b5300-3304-11ea-87e4-0329b8d2429f.png)

## Diagnostic logs
What should I do get diagnostic logs?

## Environment
![image](https://user-images.githubusercontent.com/16345479/72050634-f4502400-3304-11ea-82af-0522dc8189cf.png)

**Comment by isaiahwilliams** [comment]
@jaehungim31 when this feature was added it was done in a way to avoid breaking existing functionality. So, you will need to specify the agreement type you can do this by running the following 

```powershell
Get-PartnerCustomerAgreement -AgreementType MicrosoftCustomerAgreement
```

**Comment by jaehungim31** [comment]
> @jaehungim31 when this feature was added it was done in a way to avoid breaking existing functionality. So, you will need to specify the agreement type you can do this by running the following
> 
> ```powershell
> Get-PartnerCustomerAgreement -AgreementType MicrosoftCustomerAgreement
> ```

Thank you. Is working now.
