### ISSUE TITLE
3.0.4 release broke ability to get exchangeonline refresh token

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#254]
# Steps to reproduce
Run the command to get a new refresh token as per microsoft documentation

$token = New-PartnerAccessToken -Module ExchangeOnline

## Expected behavior
Given a device code link to enter your code and return the token

## Actual behavior
Powershell requests a scope

cmdlet New-PartnerAccessToken at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Scopes[0]: 

## Environment
partnercenter module verison 3.0.4

**Comment by isaiahwilliams** [comment]
@Shadoxity thank you for reporting this issue. This issue will be fixed with our next release which will happen in the next few days.

**Comment by isaiahwilliams** [comment]
@Shadoxity we have unlisted version 3.0.4 and just released version 3.0.5. The latest release resolves this issue. Thank you for bring it to our attention.
