### ISSUE TITLE
User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#264]
How do we resolve this? 

# Steps to reproduce

Connect to customer tenant via partner center powershell

## Expected behavior

Connect and be able to use powershell

## Actual behavior

New-PartnerAccessToken : AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. 
Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: 09c9d8b2-547b-4cea-8ab0-daae5d095900
Correlation ID: 635eb08d-38e0-4777-badc-33153b75746c
Timestamp: 2020-01-21 16:34:43Z
At line:1 char:10
+ $token = New-PartnerAccessToken -Module ExchangeOnline -RefreshToken  ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-PartnerAccessToken], MsalUiRequiredException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by Shadoxity** [comment]
Any update here? What conditional access policy would block this? This is running on a windows server

**Comment by isaiahwilliams** [comment]
@Shadoxity would it be possible for you to share the details regarding the parameters you are using and what operating system you are using?

**Comment by Shadoxity** [comment]
@isaiahwilliams 
It is using the what the partner center powershell details to connect to exchange online via partner with refresh token.
Running in powershell on Server 2016 datacenter.
Which I would of imagined that would say the operating system is "Windows" and the conditional access policy would allow it.

More or less this


	$token = New-PartnerAccessToken -Module ExchangeOnline -RefreshToken $RefreshToken -Tenant $customerId

	$tokenValue = ConvertTo-SecureString "Bearer $($token.AccessToken)" -AsPlainText -Force
	$credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)

	$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid?DelegatedOrg=$($customerId)&BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection

	Import-PSSession $session -commandname get-mailbox -FormatTypeName *mailbox*

**Comment by isaiahwilliams** [comment]
@Shadoxity unfortunately I have not been able to reproduce this particular issue. Are you still blocked by it?

**Comment by isaiahwilliams** [comment]
If you are still having issues with this please feel free to reopen this issue.

**Comment by Shadoxity** [comment]
Hey @isaiahwilliams Yes now change in this! 100% still an issue.
Why does conditional access not see powershell being run from Windows as a windows device.

It is this specific command which gives the error
	$token = New-PartnerAccessToken -Module ExchangeOnline -RefreshToken $RefreshToken -Tenant $customerId


New-PartnerAccessToken : AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and 
Windows flavors.
Trace ID: 2bd7b201-acc4-4338-b365-e4ec5c190100
Correlation ID: 61387f9a-c56d-4816-ae1c-bbc1f904c011
Timestamp: 2020-03-21 05:31:09Z
At line:1 char:11
+ ...    $token = New-PartnerAccessToken -Module ExchangeOnline -RefreshTok ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-PartnerAccessToken], MsalUiRequiredException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken

**Comment by isaiahwilliams** [comment]
@Shadoxity what version of the module are you using?

**Comment by Shadoxity** [comment]
@isaiahwilliams The most recent test was with 3.0.7

**Comment by nmaarse** [comment]
Hi, when running: az account get-access-token --resource-type=ms-graph --tenant [mytenantid] i get the same error:
_'AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: 49d4b937-43eb-4053-b62a-d88cc97a1900
Correlation ID: 482427ab-ccb1-415c-b12d-4260532f916b
Timestamp: 2021-09-22 13:50:44Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default'_

my az version is:
_az --version
azure-cli                         2.28.0

core                              2.28.0
telemetry                          1.0.6

Extensions:
account                            0.2.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\niekm\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy_

running az in the cloud shell in portal.azure.com i do get a token back.

Any clue how to solve this?
