### ISSUE TITLE
New-PartnerAccessToken : AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access

### ISSUE THREAD

**Issue by kkalicharan** [microsoft/Partner-Center-PowerShell#269]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs
> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.
Trace ID: d77ca18e-f593-4f89-a0cf-a373ec94bd00
Correlation ID: a3aea677-4c7a-4f87-bf62-29cc002dfa30
Timestamp: 2020-01-27 19:46:24Z

## Environment

> Please share additional details about your environment.
> Version

**Comment by isaiahwilliams** [comment]
@kkalicharan based on what you have shared it sounds like your refresh token has expired. You will need to generate a new one using an account that has multi-factor authentication enforced.

**Comment by isaiahwilliams** [comment]
@kkalicharan if you are still having issues with this please let us know.

**Comment by kkalicharan** [comment]
> @kkalicharan if you are still having issues with this please let us know.

Confirming that generating new tokens resolved the issue.
