### ISSUE TITLE
Bug in Get-PartnerCustomerDeviceBatch, Dont give batch creation date

### ISSUE THREAD

**Issue by Crille77** [microsoft/Partner-Center-PowerShell#281]
# Steps to reproduce
Login to PartnerCenter via this Powershell Module
run command "Get-PartnerCustomerDeviceBatch -CustomerId $CustomerID"

## Expected behavior
To see the creationdate all batches
## Actual behavior
<img width="438" alt="Get-PartnerCustomerDeviceBatch-Bug2" src="https://user-images.githubusercontent.com/3750070/75299788-4c4fd500-5836-11ea-924b-4fbcc8a1a9d0.png">

> What is the behavior observed?
Looks like DeviceCount is repeted instead of displaying the creationdate for the batch

**Comment by isaiahwilliams** [comment]
@Crille77 thank you for sharing the information with us. This is an issue with the formatting, and you can work around it by deleting the [Microsoft.Store.PartnerCenter.PowerShell.format.ps1xml](https://github.com/microsoft/Partner-Center-PowerShell/blob/master/src/PowerShell/Microsoft.Store.PartnerCenter.PowerShell.format.ps1xml) file

**Comment by isaiahwilliams** [comment]
The required code changes for this issue have been made. A new version of the module will be available by this Friday that includes this fix.
