### ISSUE TITLE
Get-PartnerOffer does not list Azure Plans

### ISSUE THREAD

**Issue by cblackuk** [microsoft/Partner-Center-PowerShell#289]
# Steps to reproduce

```powershell
Get-PartnerCustomerAzurePlanEntitlement -CustomerId "xxxx-xxxx-xxxx-xxxx-xxxxx" -SubscriptionId "xxxx-xxxx-xxxx-xxxx-xxxxx" | Select-Object -Property *

FriendlyName              Id                                   Status SubscriptionId
------------              --                                   ------ --------------
Microsoft Azure - UKCloud xxxx-xxxx-xxxx-xxxx-xxxxx active xxxx-xxxx-xxxx-xxxx-xxxxx
```

```powershell
$GetOrders = Get-PartnerCustomerOrder -CustomerId "xxxx-xxxx-xxxx-xxxx-xxxxx" | select *
$GetOrders.LineItems | Where-Object -Property OfferId -like "DZH318Z0BPS6:0001:DZH318Z0BMGV"


FriendlyName         : Azure plan
LineItemNumber       : 0
OfferId              : DZH318Z0BPS6:0001:DZH318Z0BMGV
PartnerIdOnRecord    :
ParentSubscriptionId :
Pricing              :
ProvisioningContext  : {}
Quantity             : 1
SubscriptionId       : xxxx-xxxx-xxxx-xxxx-xxxxx
TermDuration         :
TransactionType      : New
```

```powershell
Get-PartnerOffer | Where-Object -Property OfferId -like "*DZH318Z0BPS6:0001:DZH318Z0BMGV*"
Get-PartnerOffer | Where-Object -Property OfferId -like "*DZH318Z0BPS6*"
```

## Expected behavior

Should return Partner Offer.

## Actual behavior

Does not find anything related to Azure Plans. Azure Plans cannot be found in the Get-PartnerOffer even in the whole list exported to a file. No mention of Azure Plans anywhere.

## Environment

```powershell
 Get-Module -Name PartnerCenter

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.7      PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter...}
```

This essentially prevents any automation related to Azure Plans. As if we cannot query the offer, we cannot create the offer.

**Comment by cblackuk** [comment]
@isaiahwilliams help please?

**Comment by isaiahwilliams** [comment]
You will need to use the products feature to get the information required to create an Azure Plan. Details on how this can be accomplished using the API can be found [here](https://docs.microsoft.com/partner-center/develop/create-azure-plan). You can use information as a guide to get the details request for the [Add-PartnerCustomerCartLineItem](https://docs.microsoft.com/en-us/powershell/module/partnercenter/add-partnercustomercartlineitem?view=partnercenterps-3.0) command.

**Comment by cblackuk** [comment]
I found it after I posted it but I thought it should still appear in the Offer? If not, we can close it off. Thanks @isaiahwilliams

**Comment by isaiahwilliams** [comment]
This is the expected behavior, so I will be closing this issue.
