### ISSUE TITLE
Cannot use New-PartnerCustomerAgreement

### ISSUE THREAD

**Issue by andrew951** [microsoft/Partner-Center-PowerShell#292]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

```
New-PartnerCustomerAgreement -AgreementType MicrosoftCloudAgreement -TemplateId 998b88de-aa99-4388-a42c-1b3517d49490 -ContactEmail $customer.CloudEmailAddress -ContactFirstName $customer.CloudFirstName -ContactLastName $customer.CloudLastName -ContactPhoneNumber $customer.CloudPhoneNumber -CustomerId $tenantId
```

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

```
New-PartnerCustomerAgreement : Microsoft Cloud Agreement Template ID '998b88de-aa99-4388-a42c-1b3517d49490' is no
longer supported.
At line:1 char:1
+ New-PartnerCustomerAgreement -AgreementType MicrosoftCloudAgreement - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-PartnerCustomerAgreement], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerCustomerAgreement
```

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.7      PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserR...
```

## Other Notes

`Get-PartnerAgreementDetail` shows the correct template id as shown below:
```
Get-PartnerAgreementDetail

AgreementLink                                              AgreementType           TemplateId
-------------                                              -------------           ----------
https://docs.microsoft.com/en-us/partner-center/agreements MicrosoftCloudAgreement 998b88de-aa99-4388-a42c-1b3517d49490
```

However, running `Get-PartnerAgreementDocument -TemplateId 998b88de-aa99-4388-a42c-1b3517d49490` results in the following
```
Get-PartnerAgreementDocument : An agreement document for template ID '998b88de-aa99-4388-a42c-1b3517d49490' in
language 'en-US' and for country 'US' was not found.
At line:1 char:1
+ Get-PartnerAgreementDocument -TemplateId 998b88de-aa99-4388-a42c-1b35 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-PartnerAgreementDocument], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerAgreementDocument
```

**Comment by marcelbraak** [comment]
Hi Andrew,
I think you get this error "Microsoft Cloud Agreement Template ID '998b88de-aa99-4388-a42c-1b3517d49490' is no longer supported." because the Microsoft Cloud Agreement is deprecated and replaced by the "Microsoft Customer Agreement"
The Microsoft Customer Agreement ID we use is

Please try with this ID:
$agreementTemplateID = '117a77b0-9360-443b-8795-c6dedc750cf9' # Microsoft Customer Agreement Template ID

Could be each language of the template has a different ID but i dont know for sure.
This one is working for us, but it could be it's the dutch one.

Best Regards,
Marcel

**Comment by andrew951** [comment]
@marcelbraak That looked like it worked! How were you able to find this particular Template ID?

**Comment by marcelbraak** [comment]
Great to hear.
I could not find any documentation source on the template id's anywhere so what i have done is:
I created a new CSP tenant using the GUI and accepted the Microsoft Customer Agreement.
Then i used the Get-PartnerCustomerAgreement to retrieve the just accepted agreement details which containers the Template ID :)

If anyone has information on where these templates ID's a are documented please share.

**Comment by isaiahwilliams** [comment]
@andrew951 you can use the [Get-PartnerAgreementDetail](https://docs.microsoft.com//powershell/module/partnercenter/get-partneragreementdetail) to get a list of agreement types. @marcelbraak is correct that the Microsoft Cloud Agreement has been replaced by the Microsoft Customer agreement.

**Comment by andrew951** [comment]
@isaiahwilliams if you look at my example above, I only have one agreement showing, and it shows the Microsoft Cloud Agreement
```
Get-PartnerAgreementDetail

AgreementLink                                              AgreementType           TemplateId
-------------                                              -------------           ----------
https://docs.microsoft.com/en-us/partner-center/agreements MicrosoftCloudAgreement 998b88de-aa99-4388-a42c-1b3517d49490
```

**Comment by marcelbraak** [comment]
Try with -AgreementType All:

`Get-PartnerAgreementDetail -AgreementType All

AgreementLink                                              AgreementType              TemplateId                           VersionRank
-------------                                              -------------              ----------                           -----------
https://aka.ms/customeragreement                           MicrosoftCustomerAgreement 117a77b0-9360-443b-8795-c6dedc750cf9           0
https://docs.microsoft.com/en-us/partner-center/agreements MicrosoftCloudAgreement    998b88de-aa99-4388-a42c-1b3517d49490           0`

**Comment by isaiahwilliams** [comment]
You will need to specify the [AgreementType](https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partneragreementdetail?view=partnercenterps-3.0#parameters) parameter. When making the call to the Partner Center API you need to specify the agreement type or use a star to indicate you want all of them back. That functionality was mirrored in this module to avoid breaking any existing scripts that were not expecting an array returned from that command.

**Comment by andrew951** [comment]
Got it. That worked. Could I request that we update the example located at https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partnercustomeragreement?view=partnercenterps-3.0

**Comment by isaiahwilliams** [comment]
The sample will be updated with our next release. Thank you for the feedback
