### ISSUE TITLE
Exchange sample and Basic authentication

### ISSUE THREAD

**Issue by christianarg** [microsoft/Partner-Center-PowerShell#296]
The exchange sample shown here https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0

$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid?DelegatedOrg=$($customerId)&BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection

Uses -Authentication Basic although the querystring shows &BasicAuthToOAuthConversion=true

So I can infer that is using basic auth but converting it to oauth :) My question is, in regarding to exchange retiring basic authentication in Octover 2020 (I think they delayed it unitl 2021 because of the covid crisis but the next question remains), will the sample continue to work after basic auth is retired??

https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/

**Comment by isaiahwilliams** [comment]
You are correct, due to the query string parameter basic authentication is jot happening. This approach is using OAuth and you will not be impacted by the changes happening with the Office 365 platform in terms of disabling basic authentication

**Comment by christianarg** [comment]
Thx
