### ISSUE TITLE
Add-PartnerCustomerCartLineItem not adding item to existing cart

### ISSUE THREAD

**Issue by mprentice22153** [microsoft/Partner-Center-PowerShell#297]
I can use the New-PartnerCustomerCart command to create a cart with a single item, and I can see the cart item with
get-partnercustomercart -CartId $CustomerCart.CartID -CustomerId $customerID

If I create a new LineItem, the LineItems in the cart never changes from {0} as I attempt to add items using
Add-PartnerCustomerCartLineItem -CartId $customerCart.CartID -CustomerId $CustomerID -LineItem $lineItem
I've tried with and without setting a different ID number in the LineItem object.

This command only ever displays the first cart item:
(get-partnercustomercart -CartId $CustomerCart.CartID -CustomerId $customerID).lineitems

I've successfully added multiple LineItems to an array and created a new cart, but what if I want to create a cart with an item, then add another item to the cart, then add another item to the cart.  Do I need to keep an array and just discard the carts until I get my final cart?

It seems like Add-PartnerCustomerCartLineItem is not working properly.

Thank you,

Matthew

**Comment by isaiahwilliams** [comment]
@mprentice22153 re you still having issues with this?

**Comment by isaiahwilliams** [comment]
If you are still having issues with this, please re-open this issue.
