### ISSUE TITLE
Secure app model with exchange online operations fails on some "write" operations like converting to shared mailbox

### ISSUE THREAD

**Issue by christianarg** [microsoft/Partner-Center-PowerShell#298]
We're using this https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0#exchange-online-powershell to succesfully connect to our customers exchange with the secure application model. We can perform operations like get-mailbox correctly.
But converting to shared mailbox and other "write" operations fail with permissions error.

We found this article https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/16550560-delegated-admin-partner-able-to-convert-tennant?page=2&per_page=20 and because (if we understood it correctly) the secure app model basically uses the token of a user with delegated permissions this could be the problem.

We need help to determine the problem (or confirm if the possible problem citied above) and help us solve the problem.

If MS is forcing us to implement secure app model but exchange online powershell does not work correctly then we need an alternative solution

**Comment by isaiahwilliams** [comment]
@christianarg these operations should be possible if you are leveraging an account from the partner tenant that has delegated admin privileges over the customer. It is my understanding this problem occurs when connecting interactive when MFA is enforced as well. So, I would recommend that you open support ticket, that way the Exchange Online teams can get engaged.

**Comment by christianarg** [comment]
@christianarg I opened a support ticket with our premier support on office portal and they kindly told me they had nothing to do with this exchange online powershell problem as this was something from delegated permissions and I should open a support ticket on the partner center, which I did. I opened this issue here "in pararalell" hopoing that between all this tickets that I have to open, someone gives us a solution (not getting there for now)

**Comment by isaiahwilliams** [comment]
@christianarg I have managed to discover the root cause for this issue. This can happen when you are using the customer identifier instead of the domain for the customer when establishing the connection. You can resolve by using the `customer.onmicrosoft.com` domain when connecting instead of the customer identifier. Our documentation on this will be updated in the coming days to reflect this modified guidance. I hope this information helps!

**Comment by isaiahwilliams** [comment]
Our [documentation](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0) on this topic has been updated and published.
