### ISSUE TITLE
Retrieve ImmutableID with Get-PartnerCustomerUser

### ISSUE THREAD

**Issue by johandehaan** [microsoft/Partner-Center-PowerShell#30]
# Feature Request

My customers would like to have a clear image of the users on premises and the usage of licences in Office 365. If I have the `ImmutableID`, I can connect that one with the `ObjectGUID` on the AD User.

If I retrieve a user with `Get-PartnerCustomerUser` I would like to find an attribute like `ImmutableID`. This is possible with the Module MSOnline, but I haven't found the same option in PartnerCenter.

**Comment by isaiahwilliams** [comment]
Hi @johandehaan, 

Thank you for opening this feature request. Currently the Partner Center API/SDK does not return the immutable identifier for users. So, we would have to leverage Microsoft Graph to gather this information. With the current design this module is only interacting with the Partner Center API, but we are considering connecting to other APIs to include additional functionality and information. I will keep you posted with respect to our decision making.

**Comment by isaiahwilliams** [comment]
Hi @johandehaan,

This will be included in the next release. Our hope is to have the release available early this week.

**Comment by isaiahwilliams** [comment]
Version 1.5.1905.1 was just released. Please update and you will find the ability to get this information. Currently the Partner Center API does not support setting it.

**Comment by johandehaan** [comment]
Hi @isaiahwilliams 

I've updated the module and I just tried to retrieve this information, but I don't see the property when I retrieve a users' properties:

```
PS C:\> Get-Module PartnerCenter

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.5.1905.1 partnercenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter...}
PS C:\> $CustomerUser = Get-PartnerCustomerUser -CustomerId $CustomerId -UserId $customerUserId
PS C:\> $CustomerUser | gm


   TypeName: Microsoft.Store.PartnerCenter.PowerShell.Models.CustomerUsers.PSCustomerUser

Name                  MemberType Definition
----                  ---------- ----------
Equals                Method     bool Equals(System.Object obj)
GetHashCode           Method     int GetHashCode()
GetType               Method     type GetType()
ToString              Method     string ToString()
DisplayName           Property   string DisplayName {get;set;}
FirstName             Property   string FirstName {get;set;}
LastDirectorySyncTime Property   System.Nullable[datetime] LastDirectorySyncTime {get;set;}
LastName              Property   string LastName {get;set;}
SoftDeletionTime      Property   System.Nullable[datetime] SoftDeletionTime {get;set;}
State                 Property   Microsoft.Store.PartnerCenter.Models.Users.UserState State {get;set;}
UsageLocation         Property   string UsageLocation {get;set;}
UserDomainType        Property   Microsoft.Store.PartnerCenter.Models.Users.UserDomainType UserDomainType {get;set;}
UserId                Property   string UserId {get;set;}
UserPrincipalName     Property   string UserPrincipalName {get;set;}

```

What am I doing wrong?
