### ISSUE TITLE
Getting the below issue when running - Install-Module -Name PartnerCenter -AllowClobber -Scope CurrentUser

### ISSUE THREAD

**Issue by balarjrao** [microsoft/Partner-Center-PowerShell#300]
# Steps to reproduce

I run powershell ISE as adminstrator and run the below script.
Install-Module -Name PartnerCenter -AllowClobber -Scope CurrentUser

I got the below issue when the running the above script.

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'PartnerCenter'. Try 
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior

It is supposed to Installl
> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by isaiahwilliams** [comment]
@balarjrao the appropriate changes to correct this issue have been made. Later today version 3.0.9 will be released which includes this hotfix.
