### ISSUE TITLE
No data after switching to azure plan

### ISSUE THREAD

**Issue by TimVonVarendorff** [microsoft/Partner-Center-PowerShell#305]
Hello,
im using this module (v 3.0.9.) to get all data that belongs to our customers in azure. I collect data to make it visible with Power Bi.  After switching every subscription to azure plan we can't get any new data.

Get-PartnerCustomerSubscriptionUtilization (with proper parameters)
should get me the data like before, but first it returned an error:

"Get-PartnerCustomerSubscriptionUtilization : Subscription id 'xxxxx' provided was not found under this customer."

After searching I got the information, that I can get the subscription with :
Get-PartnerCustomerAzurePlanEntitlement -CustomerId "xxx" -SubscriptionId  "yyy"

I can use the response to get data before switching to azure plan but not data after the switching date.

for example:

#data before azure plan
$data1 = Get-PartnerCustomerSubscriptionUtilization -CustomerId "xxx" -SubscriptionId "yyy" -StartDate (Get-Date -day 1 -hour 0 -minute 0 -second 0 -Month 1) -EndDate (Get-Date -day 7 -hour 0 -minute 0 -second 0 -Month 1)  -Granularity Daily -ShowDetails
$data1.Count 

This call holds data like before.

#data after switching to azure plan
$data4 = Get-PartnerCustomerSubscriptionUtilization -CustomerId "xxx" -SubscriptionId "yyy" -StartDate (Get-Date -day 1 -hour 0 -minute 0 -second 0 -Month 4) -EndDate (Get-Date -day 7 -hour 0 -minute 0 -second 0 -Month 4)  -Granularity Daily -ShowDetails
$data4.Count

This call return null even though there has to be data.

Is this an expected behavior?

**Comment by Woody1193** [comment]
Sorry, I'm not a Microsoft representative or anything but I ran into this problem as well. The explanation for this behavior falls under the Microsoft documentation, [here](https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-s-utilization-record-for-azure#prerequisites). I hope this helps.

**Comment by TimVonVarendorff** [comment]
Thanks. I missed that information.
