### ISSUE TITLE
Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown

### ISSUE THREAD

**Issue by brandilton** [microsoft/Partner-Center-PowerShell#306]
To note:
-we are indirect resellers under Synnex.  Should we be able to run Partner-Center-Powershell commands like Get-PartnerCustomerSubscription at all?

(been editing this issue as I make two steps forward, one step back)

here's where I'm currently stuck:

code:
```
$appId = 'myAppID' 
$appSecret = 'myAppSecre' | ConvertTo-SecureString -AsPlainText -Force 
$credential = New-Object System.Management.Automation.PSCredential $appId, $appSecret
$PartnerTenantID = 'myTenantGUID'
$pcRefreshToken = 'myRefreshToken'

$pcToken = New-PartnerAccessToken -RefreshToken $pcRefreshToken -Credential $credential -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ApplicationId $appId -ServicePrincipal -Tenant $PartnerTenantID -ErrorVariable ExpiredToken
Connect-PartnerCenter -AccessToken $pcToken.AccessToken
Get-PartnerCustomerSubscription -CustomerId 'myCustomersTenantID'
```
output:
```
Get-PartnerCustomerSubscription : Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown.
At line:1 char:1
+ Get-PartnerCustomerSubscription -CustomerId 601...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-PartnerCustomerSubscription], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerSubscription
```

**Comment by isaiahwilliams** [comment]
@brandilton since you are indirect reseller there will be some features of the Partner Center API that do not work for you. While you are able to get a list of customers you will not be able to get a list of subscriptions. Currently this is a limitation of the API, and it is the root cause for the error that you are receiving when you invoking the command.

**Comment by brandilton** [comment]
Thanks @isaiahwilliams .  Do you know if there's a list of what I can and cannot view as an indirect reseller?  And what I'm really after at the end of the day is a way to find out which of the clients in our partner center (we are delegated admin for many that we are not also resellers for) are non-profits.  Any ideas on how I may be able to do that?  If I run Get-MsolSubscription on a non-profit or a for profit, it shows the same SKU number regardless of if they actually pay or not.

**Comment by isaiahwilliams** [comment]
@brandilton with respect to determining which customers you have DAP with, Microsoft Graph can be used to get this information. The request to get [contracts](https://docs.microsoft.com/graph/api/contract-list) will give you a list of customers and the type of relationship you have with them. You will be looking for a contract type value of `3` which means you have a CSP and DAP relationship with a given customer. 

I cannot remember off the top of my head if `Get-MsolSubscription` provides any information on what type of subscription was used to generate the license. If it does, that would be the only way I know how to achieve what you are attempting.

**Comment by isaiahwilliams** [comment]
If there are any additional questions about the Partner Center PowerShell module please let us know.
