### ISSUE TITLE
A parameter cannot be found that matches parameter name 'id'

### ISSUE THREAD

**Issue by AnthonyKersten** [Microsoft/Partner-Center-PowerShell#31]
# Steps to reproduce

In Azure Functions I've uploaded the Partnercenter module 1.5.1810.6 using FTP. I've loaded the module from within the Azure function successfully. After this I called:

```
$ApplicationId = 'xxxxxxx'
Connect-PartnerCenter -ApplicationId $ApplicationId -Credential $O365Credential
```

## Expected behavior

This should connect me to the PartnerCenter.

## Actual behavior

The error I get is that the parameter: ID is not found

## Diagnostic logs

```
: A parameter cannot be found that matches parameter name 'id'.
at run.ps1: line 45
+ 
+ 
    + CategoryInfo          : InvalidArgument: (:) [Connect-PartnerCenter], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Store.PartnerCenter.PowerShell.Commands.ConnectPartnerCenter,run.ps1
```

**Comment by isaiahwilliams** [comment]
Hi @AnthonyKersten, 

An updated version of the module will be available early next week, that will solve this issue. Thank you for bringing this issue to my attention. If you have any other issues please let me know.

**Comment by isaiahwilliams** [comment]
Hi @AnthonyKersten, 

Version  [1.5.1811.1](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1811.1)  was just released. It includes the solution for this issue and several other updates. Once you update this issue will be resolved. Please let us know if you have any other feedback.
