### ISSUE TITLE
I get exceptions no matter what I run

### ISSUE THREAD

**Issue by mpt-austin** [microsoft/Partner-Center-PowerShell#310]
Does this work with Indirect CSPs?
Do Indirect CSPs need their Direct CSPs to enable something?

----------------------

PS C:\WINDOWS\system32> Get-PartnerAgreementDetail -AgreementType All
Get-PartnerAgreementDetail : Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown.
At line:1 char:1
+ Get-PartnerAgreementDetail -AgreementType All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-PartnerAgreementDetail], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerAgreementDetail

--------------------

PS C:\WINDOWS\system32> Get-PartnerCustomerSubscriptionUtilization -CustomerId $customerid -SubscriptionId $subscriptionid -StartDate $dateoffset -Granularity Hourly -ShowDetails
Get-PartnerCustomerSubscriptionUtilization : Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was 
thrown.
At line:1 char:1
+ Get-PartnerCustomerSubscriptionUtilization -CustomerId 329e833f-820b- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-PartnerCust...tionUtilization], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerSubscriptionUtilization

**Comment by isaiahwilliams** [comment]
@mpt-austin thank you for opening this issue. This module leverages the Partner Center API to perform almost all of the operations. Since you are an indirect reseller there currently only one operation, that I am aware of, that will work for you. That is the operation to list customers. All others will fail because the Partner Center API currently does not support indirect resellers. This feedback has been shared with the product team responsible for the API. 

Right I do not have any details to share regarding if this support will be added. Currently you best option is to work with your indirect provider to see if they have API that you can interact with.

**Comment by mpt-austin** [comment]
Thanks for the quick response and info

Sent from my iPhone

On Jun 6, 2020, at 3:28 PM, Isaiah Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


@mpt-austin<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpt-austin&data=01%7C01%7Cmichael.lavallee%40micropulsetech.com%7C6b3d237cb9c84357eefe08d80a583753%7C137c7cc39d5043dbb32560e3a8b4e7ff%7C0&sdata=yv%2FAIl53VQzd4HwBftdjYQA16GTK3NzQqbBU%2F6zuGdc%3D&reserved=0> thank you for opening this issue. This module leverages the Partner Center API to perform almost all of the operations. Since you are an indirect reseller there currently only one operation, that I am aware of, that will work for you. That is the operation to list customers. All others will fail because the Partner Center API currently does not support indirect resellers. This feedback has been shared with the product team responsible for the API.

Right I do not have any details to share regarding if this support will be added. Currently you best option is to work with your indirect provider to see if they have API that you can interact with.
