### ISSUE TITLE
The operation was canceled everywhere.

### ISSUE THREAD

**Issue by towhereur** [microsoft/Partner-Center-PowerShell#319]
# Steps to reproduce
Used version : PartnerCenter 3.0.9  
PSEdition Core 7.0.2
I successfully logged in as AppPlusUser.
Connect-PartnerCenter -AccessToken $token.AccessToken | Out-Null #AppPlusUser

## Expected behavior
No Error occurred when I ran script 3 months ago with PartnerCenter 1.5 / PSEdition Desktop 5.1.
I modified script to run on PartnerCenter 3.0.9 and too many error occurred so I wrap it with while but it doesn't help.
I'm now running on clean Azure VM PS 5.1 and PartnerCenter 1.5.1908.1 with original script, it is 5-6 times slower compared to the past.(Get-PartnerAzureRateCard needs 120 secs. which were 20 secs.) but, no errors yet,
> Share the expected output

## Actual behavior

> What is the behavior observed?
👎 Get-PartnerAzureRateCard : 20% failed.
Get-PartnerAzureRateCard -Currency $currency -Region $region
Get-PartnerAzureRateCard: C:\Users\shlim\OneDrive - Zenith&Company\Work\Script\Get-CSPConsumptionCost.ps1:111:21
Line |
 111 |  … $rateCard = Get-PartnerAzureRateCard -Currency $currency -Region $reg …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The operation was canceled.

👎 Get-PartnerCustomerSubscriptionUtilization : over 95% failed and too slow.
Get-PartnerCustomerSubscriptionUtilization -CustomerId $customer.customerID -SubscriptionId $subscription.EntitlementId -ShowDetails -StartDate $startDate -EndDate $endDate -Granularity:$granularity

**Comment by isaiahwilliams** [comment]
@towhereur there have been a few reports about timeouts, and I think this might be related to a performance issue with the Partner Center API. To help avoid any issue with this module I have increased the HTTP timeout with 3.0.10 release. Can you update to the latest version and see if you are still encountering the task was cancelled exceptions? 

With respect to the response time from the API, I would recommend that you open a support ticket through Partner Center.

**Comment by isaiahwilliams** [comment]
Please let us know if you are still having issues.
