### ISSUE TITLE
Get-PartnerContract -DomainName FQDN

### ISSUE THREAD

**Issue by skille** [Microsoft/Partner-Center-PowerShell#32]
We would like to retrieve a tenant ID based on customer domain name.

Like we could in old MSOnline Module (Get-MsolPartnerContract -DomainName FQDN.
This is needed as input for Get-PartnerCustomer -CustomerID to get a certain customer

**Comment by isaiahwilliams** [comment]
Hi @skille, 

In the next release we will be adding a parameter to the Get-PartnerCustomer command that will enable this functionality. The code has already been added, but we have not updated PowerShell Gallery just yet. Our hope is to have an updated version published later this week.

**Comment by isaiahwilliams** [comment]
Hi @skille, 

We have just deployed version [1.5.1811.1](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1811.1) and it adds the functionality to search for a customer using the onmicrosoft.com domain. Please let us know if you have any other feedback.

**Comment by skille** [comment]
This is great, but it does not work with customer email domain. 
No customers is using the .onmicrosoft.com domain.
The cmdlet should support customer domain, like the MSOnline module does.
