### ISSUE TITLE
MS KB List

### ISSUE THREAD

**Issue by 655321-Alex** [microsoft/Partner-Center-PowerShell#336]
I'm attempting to get a Complete List of MS KB's with details that include not only Security Updates but also Product Updates. I can't seems to find everything I'm looking for when using the MSRC API in Powershell.

**Comment by joelst** [comment]
@655321-Alex  You may want to check out the [repo for the MRSC API](https://github.com/Microsoft/MSRC-Microsoft-Security-Updates-API) to see if they would be able to assist.

**Comment by 655321-Alex** [comment]
Thank You, I'll check it out.
