### ISSUE TITLE
Refresh the tokens without user interaction

### ISSUE THREAD

**Issue by kfear27** [microsoft/Partner-Center-PowerShell#339]
# Feature Request

**Is your feature request related to a problem? Please describe.**
I am unable to refresh the token without user interaction, we have a function that renews however PowerShell spawns a browser we must sign into, along with a URL + code combo.

We simply want to automate this process.

**Describe the solution you would like**
A cmdlet option to obtain a new token without any user interaction

**Describe alternatives you have considered**
I have a script I can run every 90d or so but am looking to avoid doing this manual process

**Additional context**
I do not believe there is any additional context needed here but please do ask if need

My function below which works but does require user interaction

```powershell
Function Get-RefreshedTokens {
    $ApplicationId = 'OBFUSCATED'
    $ApplicationSecret = 'OBFUSCATED' | Convertto-SecureString -AsPlainText -Force
    $TenantID = 'OBFUSCATED' 
    $Credential = New-Object System.Management.Automation.PSCredential($ApplicationId, $ApplicationSecret)
    $Token = New-PartnerAccessToken -ApplicationId $ApplicationId -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Credential $Credential -Tenant $TenantID -UseAuthorizationCode
    $ExchangeToken = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant $TenantID -UseDeviceAuthentication
    Return [PSCustomObject]@{
        TenantId      = $TenantID
        Credential    = $Credential
        RefreshToken  = $Token.RefreshToken
        ExchangeToken = $ExchangeToken.RefreshToken
    }    
}

$Tokens = Get-RefreshedTokens
```

**Comment by Agazoth** [comment]
In line 7 replace  ```-UseAuthorizationCode``` with ```-RefreshToken $Token.Refreshtoken```
In line 8 replace ```'a0c73c16-a7e3-4564-9a95-2bdf47383716' ```with ```$ApplicationId```

That should take care of the double auth obsuscate your application Id

**Comment by kfear27** [comment]
Hi @Agazoth,

The unobfuscated application ID is the one listed here on this article:
https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0

Should this be the same as my Azure AD Application ID too ?

As for the `-RefreshToken $Token.RefreshToken` can we use an existing token to refresh it (as long as it is no older than 90) ?

Thanks

**Comment by Agazoth** [comment]
Hi @kfear27,

I filed an issue on inconsistent documentation on that page. It would be nice to get it cleaned up.

ApplicetionId is always the ApplicationId of your Application. It is the same as the UserName in your Credential object.

If  you have a working RefreshToken (less then 90 days old) you can generate a new token with it. All you need to do is this:
```PowerShell
$ApplicationId = 'ApplicationIdGUID'
$SecretPassword = Read-Host -AsSecureString # Or create the secret string in another way
$credential = [pscredential]::new($ApplicationId,$SecretPassword)
$CSPTenant = 'CSPTenantGUID'
$refreshToken = 'SavedRefreshToken'

$Token = New-PartnerAccessToken -ApplicationId $ApplicationId -Credential $credential -RefreshToken $refreshToken -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Tenant $CSPTenant
```
This works for me.

If you save the refresh token from the new token every time you run your code, and you run your code with less then 90 days in between, you will never have to re-authenticate.

**Comment by kfear27** [comment]
Thank you @Agazoth I will test and confirm results soon

**Comment by Agazoth** [comment]
Hi @kfear27 

Did you have a chance to test?

**Comment by kfear27** [comment]
Hi @Agazoth,

Please forgive the lateness of my reply.
I can get this to work for the RefreshToken however renewing the Exchange token is still asking for a code.

I've tested replacing `-UseDeviceAuthentication` with the same that works for the Refresh Token but it fails.

```powershell
Function Get-RefreshedTokens {
    $ApplicationId = 'OBFUSCATED'
    $ApplicationSecret = 'OBFUSCATED' | Convertto-SecureString -AsPlainText -Force
    $TenantID = 'OBFUSCATED' 
    $Credential = New-Object System.Management.Automation.PSCredential($ApplicationId, $ApplicationSecret)
    $Token = New-PartnerAccessToken -ApplicationId $ApplicationId -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Credential $Credential -Tenant $TenantID -RefreshToken $Tokens.RefreshToken
    $ExchangeToken = New-PartnerAccessToken -ApplicationId $ApplicationId -Scopes 'https://outlook.office365.com/.default' -Tenant $TenantID -RefreshToken $Tokens.RefreshToken
    Return [PSCustomObject]@{
        TenantId      = $TenantID
        Credential    = $Credential
        RefreshToken  = $Token.RefreshToken
        ExchangeToken = $ExchangeToken.RefreshToken
    }    
}
```
The error returned is:

`
New-PartnerAccessToken : A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
`

I then added the `-ServicePrincipal -Credential $Credential`, now am stuck with the error:

`
New-PartnerAccessToken : AADSTS65001: The user or administrator has not consented to use the application with ID 'OBFUSCATED' named 'MYAPPNAME'. Send an interactive authorization request for this user and resource.
`

I am still trying to work out how to refresh the Exchange Token without user interaction, any assistance is appreciated!

Thank you

**Comment by kfear27** [comment]
Also confirming I have checked the API permissions, and granted consent for our company.

**Comment by kfear27** [comment]
I have just tested browsing to the following URL
`https://login.microsoftonline.com/sydneytech365.onmicrosoft.com/oauth2/authorize?client_id=<AppID>&response_type=code&redirect_uri=http://localhost&nonce=1234&resource=https://graph.windows.net&prompt=admin_consent`

I logged in and accepted the permissions, however am still given the following error for the ExchangeToken:
`New-PartnerAccessToken : AADSTS65001: The user or administrator has not consented to use the application with ID 'OBFUSCATED' named 'MYAPPNAME'. Send an interactive authorization request for this user and resource.`

**Comment by Agazoth** [comment]
Hi @kfear27,

According to the documentation, you need to run completely other steps to get the ExchangeOnline token. Using this token is a bit different the using the other tokens. You actually use it for authorization to a remote PowerShell session, that you then import to make the cmdlets in the remote session available in your local PowerShell session.

Please try this code:
```powershell
# Authenticate with your CSP AdminAgent account
# Save the refreshtoken you get from this command to avoid logging on again
$token = New-PartnerAccessToken -Module ExchangeOnline

$customerId = 'OBFUSCATED' # The TenantId of the customer tenant you want to work on
$customerDomainName = 'OBFUSCATED' # The domain name of the customer tenant you want to work on (customer.onmicrosoft.com)
$refreshToken = $token.refreshToken # If you just generated the token use this - else import your saved token. 
$upn = 'OBFUSCATED' # The UserPrincipalName of the CSP AdminAgent user who generated the refresh token. If you just generated the token, it is the value you find in $token.Account.Username

# Get a new token based on the (saved) refreshToken
# Once $o365token has been generated, $o365token.refreshToken should be saved as the new refreshToken to avoid expiration of the saved refreshToken
$o365token = New-PartnerAccessToken -RefreshToken $refreshToken -Scopes 'https://outlook.office365.com/.default' -Tenant $customerId -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' # This is the Application Id of the Exchange Online PowerShell Azure Active Direcotry application

$tokenValue = ConvertTo-SecureString "Bearer $($o365token.AccessToken)" -AsPlainText -Force

$credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)

$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid?DelegatedOrg=$($customerDomainName)&BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection

Import-PSSession $session
```

I hope this clarifies the documentation for you.

**Comment by kfear27** [comment]
Hi @Agazoth,

Thanks for your help, I have managed to get this working.

My current tokens are stored in a DB and captured in a different way, but for anyone else reading this thread looking for help you can use the below.

```powershell
$Tokens = @{
    "RefreshToken" = "TOKEN_HERE"
    "ExchangeToken"  = "TOKEN_HERE"
}

Function Get-RefreshedTokens {
    $ApplicationId = 'AzureApp_Id'
    $ApplicationSecret = 'AzureApp_Secret' | Convertto-SecureString -AsPlainText -Force
    $TenantID = 'Your_Tenant_Id' 
    $Credential = New-Object System.Management.Automation.PSCredential($ApplicationId, $ApplicationSecret)
    $Token = New-PartnerAccessToken -ApplicationId $ApplicationId -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Credential $Credential -Tenant $TenantID -RefreshToken $Tokens.RefreshToken
    $ExchangeToken = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant $TenantID -RefreshToken $Tokens.ExchangeToken # Use this application Id as it is the Exchange Online Id
    Return [PSCustomObject]@{
        TenantId      = $TenantID
        Credential    = $Credential
        RefreshToken  = $Token.RefreshToken
        ExchangeToken = $ExchangeToken.RefreshToken
    }    
}

```

If your tokens are current in $Tokens, it will use these and return renewed ones where you can store these wherever you need to.

Thanks !
