### ISSUE TITLE
AADSTS700025 using New-PartnerAccessToken

### ISSUE THREAD

**Issue by nbuehlmann** [Microsoft/Partner-Center-PowerShell#358]
I am trying to obtain a refresh token (to store it in an Azure KeyVault) using the example described [here](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0#consent):
```powershell
$credential = Get-Credential
New-PartnerAccessToken -ApplicationId 'xxxx-xxxx-xxxx-xxxx' -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Credential $credential -Tenant 'yyyy-yyyy-yyyy-yyyy' -UseAuthorizationCode
```
I have configured an Azure AppRegistration (Web App) and registered it in Partner Center, where I also added a new key (client secret). When prompted by `Get-Credential` I enter the AppId and Secret. In the Azure Portal I also configured a redirected uri of `http://localhost:8400` as advised by the documentation.

After entering the credentials, as expected, a browser window opens and I am able to successfully log in to my account, after which I am presented with the message:

> Authentication complete. You can return to the application. Feel free to close this browser tab.

At this point however, I get a very strange error in PowerShell:
![image](https://user-images.githubusercontent.com/33098853/116213195-db5fc200-a745-11eb-9975-60180b56e24e.png)

The error message seems particularly strange to me, as I explicitly disallowed public client flows in the Azure Portal for the AppRegistration:
![image](https://user-images.githubusercontent.com/33098853/116213778-5b862780-a746-11eb-9061-aae7a97b22ed.png)

Any ideas or help are much appreciated!🙂

**Comment by Agazoth** [comment]
Hi @TheNCuber ,

I had a similar issue some time back. It tool 3 months and a lot of MS support, but finally I managed to scrape together an instruction on how to create an Application Account that works. Try to follow these instructions:

# Setup Application account for CSP Secure Application Model on PowerShell 7.x

To execute the account setup you need Global Administrator rights on the CSP tenant

```powershell
$Context = Connect-AzAccount # Sign in with your AdminAgent credentials 
$Context = Get-AzContext
$Domain = Get-AzDomain -TenantId $Context.Tenant.Id
$DisplayName = 'CSPAutomation'

$paramsApp = @{
    DisplayName             = $DisplayName
    ReplyUrls               = 'http://localhost:8400'
    AvailableToOtherTenants = $true
    IdentifierUris          = 'https://{0}/{1}' -f $Domain.ExtendedProperties.Directory, [guid]::NewGuid().Guid
}

$App = New-AzADApplication @paramsApp
$SP = New-AzADServicePrincipal -ApplicationId $App.AppId

# Set a password for the account
$Password = [guid]::NewGuid().Guid | ConvertTo-SecureString -AsPlainText -Force
$SetPassword = New-AzADAppCredential -ObjectId $App.ObjectId -Password $Password -EndDate (Get-Date).AddYears(10)

# Add the new SP to the AdminAgents group
$AdminAgentsGroup = Get-AzADGroup -DisplayName AdminAgents
Add-AzADGroupMember -TargetGroupObjectId $AdminAgentsGroup.Id -MemberObjectId $SP.Id

```

## Manually add these API Permissions in the portal
*Unfortunately this cannot be done by PowerShell - the old Windows PowerShell AzureAD cmdlets can do this though*

Find your App in Azure AD - App registrations. You will need to look under All Applications, since the code does not add an owner.

* Azure Active Directory Graph
    * Delegated
        * Directory.AccessAsUser.All
        * User.Read
    * Application
        *Directory.Read.All

* Microsoft Graph
    * Application
        * Directory.Read.All
        * SecurityEvents.Read.All

* Partner Center API
    * Delegated
        * user_impersonation

* Azure Service Management
    * Delegated
        * user_impersonation


Remember to grant admin consent when done
<br>
<br>

# PartnerCenter modules do not work, if you have run Connect-AzAccount in the same shell
You are now able to access customer tenants by running the code below

```powershell
$ApplicationId = '' # Your Application ID 
$ApplicationSecret = '' # Your Application Secret as secure string
$credential = [pscredential]::new($ApplicationId,$ApplicationSecret)
$CSPTenantId = '' # Your CSP Tenant ID
$CustomerTenantId = '' # TenantId of the customer to work on
$TokenOwner = '' # UserPrincipalname of the AdminAgents user that generated the refreshToken

$paramSplat = @{
    ApplicationId        = $ApplicationId
    Scopes               = 'https://api.partnercenter.microsoft.com/user_impersonation'
    ServicePrincipal     = $true
    Credential           = $credential
    Tenant               = $CSPTenantId
    UseAuthorizationCode = $true
}
# Create a token with Portal login
$Token = New-PartnerAccessToken @paramSplat

# Extract refreshToken. Save it in a key vault to use it in automated code. Remember to update refreshToken inn the key vault within 90 days, or it will expire. Whit a valid refreshToken, the code below will run without portal login.
$RefreshToken = $Token.RefreshToken

#Generate a new token from the refreshToken
$paramSplat = @{
    ApplicationId        = $ApplicationId
    Scopes               = 'https://api.partnercenter.microsoft.com/user_impersonation'
    ServicePrincipal     = $true
    Credential           = $credential
    Tenant               = $CSPTenantId
    RefreshToken         = $RefreshToken
}

$Token = New-PartnerAccessToken @paramSplat

# Connect to Azure
$paramSplat = @{
    ApplicationId        = $ApplicationId
    Scopes               = 'https://management.azure.com/user_impersonation'
    ServicePrincipal     = $true
    Credential           = $credential
    Tenant               = $CustomerTenantId
    RefreshToken         = $RefreshToken
}
$azureToken = New-PartnerAccessToken @paramSplat
$paramSplat['Scopes'] = 'https://graph.windows.net/.default'
$graphToken = New-PartnerAccessToken @paramSplat

$azureParam = @{
    AccessToken = $azureToken.AccessToken
    AccountId = $TokenOwner
    GraphAccessToken = $graphToken.AccessToken 
    Tenant = $CustomerTenantId
}

Connect-AzAccount @azureParam

```

**Comment by nbuehlmann** [comment]
> Hi @TheNCuber ,
> 
> I had a similar issue some time back. It tool 3 months and a lot of MS support, but finally I managed to scrape together an instruction on how to create an Application Account that works. Try to follow these instructions:
> 
> ...
> 
> Connect-AzAccount @azureParam

The GitHub community is simply amazing. Thank you so much @Agazoth, your instructions worked like a charm 🥳!

**Comment by llvng** [comment]
Thank you so much @Agazoth - I have been trying to iterate and automate through all of my customer tenancies for hours and hours without avail and managed to borrow some code from your script to do it. Big help, thank you very much,
