### ISSUE TITLE
Get-PartnerCustomer invalid_grant

### ISSUE THREAD

**Issue by StephaneChauveau** [Microsoft/Partner-Center-PowerShell#373]
Hello,

Get-PartnerCustomer
**Get-PartnerCustomer :  (invalid_grant) error**

MS Graph + Partner Center API Given Rights.
My authentication is :
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $ApplicationSecret

**Comment by josvlict** [comment]
We experience the same issue, is there a solution for this perhaps?

**Comment by tmidthjell** [comment]
Might the reason be that Microsoft Partner Center API isnt supported for indirect resellers?

**Comment by StephaneChauveau** [comment]
no we are tier one.
