### ISSUE TITLE
Get-PartnerCustomer -Domain $CustomerDomain

### ISSUE THREAD

**Issue by skille** [microsoft/Partner-Center-PowerShell#40]
No customers is using the .onmicrosoft.com domain.
The cmdlet should support customer domain, like the MSOnline module does.

_Originally posted by @skille in https://github.com/Microsoft/Partner-Center-PowerShell/issues/32#issuecomment-439345001_

**Comment by isaiahwilliams** [comment]
This functionality will be delivered with the next release of the module. With the recent integration with Microsoft Graph, it is now possible to query for customers based on the default domain.

**Comment by isaiahwilliams** [comment]
I have just released version [2.0.1911.4](https://www.powershellgallery.com/packages/PartnerCenter/2.0.1911.4) that contains the ability to get customers based on their default domain.
