### ISSUE TITLE
Comandlets for GDAP

### ISSUE THREAD

**Issue by M6Ka7** [Microsoft/Partner-Center-PowerShell#401]
# Feature Request / Question

Is it planed to create commands for accessing / creating / managing [GDAP Partner Relationships](https://learn.microsoft.com/en-us/partner-center/gdap-introduction)?

Microsoft links in the [GDAP - FAQ](https://learn.microsoft.com/en-us/partner-center/gdap-faq#gdap-api) to an [API - Overview](https://learn.microsoft.com/en-us/partner-center/develop) where this project is listed, but can't find these endpoints yet.

Kind regards
    Michael

**Comment by courtimus** [comment]
I've opened a ticket with partner support to see if I can get any help on this. Some cmdlets work with GDAP while others don't. I recommend anyone who can also open with Microsoft partner support. 

They initially told me to check out this github page, and I've since requested they escalate the issue.

**Comment by slavizh** [comment]
@courtimus it is useless. This module is not officially supported by MSFT. What they will tell you is that it is community module and anyone can contribute to it. More than an year ago I have tried to convince MSFT to support the module trough various channels - support, partner programs, personal connections, etc., reaching different levels in the hierarchy . The answer is always no, they will not support the module.

**Comment by jonwbstr** [comment]
How does someone contribute to an abandoned github project? I don't see anyone around to even grant write access to the community project.

**Comment by weyCC81** [comment]
It doesn't look good or do i not read this right?: https://learn.microsoft.com/en-us/partner-center/announcements/2023-january#exchange-online-automation-affecting-change-on-march-31-2023

> The Legacy Exchange Online Public Client ID (app ID a0c73c16-a7e3-4564-9a95-2bdf47383716) will be retired on March 31, 2023. The legacy public client was previously used by the open-source Partner Center PowerShell module (GitHub here).

**Comment by M6Ka7** [comment]
This project seems to be dead. We solved it with the [Rest API](https://learn.microsoft.com/en-us/partner-center/developer/partner-center-rest-api-reference) which is also supported with an official partner support contract.
