### ISSUE TITLE
Get-PartnetCustomerSubscription: Requested value 'Disabled' was not found

### ISSUE THREAD

**Issue by PierreGPOST** [Microsoft/Partner-Center-PowerShell#403]
Hi,

i have a trouble with some customers, getting the list of subscription. Since nearly one month, as one subscription is in 'Disabled' state, i cannot get the list of subscriptions for those customers

Running the command Get-PartnerCustomerSubscribedSku -CustomerId '*******-xxxx-******-xxxx-4687a1abxxx' is working fine, showing me the CapabilityStatus as 'Disabled' wihout issues.

But this command does not work anymore, so i cannot get the orderId and other informations about the subscription:
Get-PartnerCustomerSubscription -CustomerId '*******-xxxx-******-xxxx-4687a1abxxx'

And i receive the result:
Get-PartnerCustomerSubscription : Requested value 'Disabled' was not found.
At line:1 char:1
+ Get-PartnerCustomerSubscription -CustomerId 'feea32a5-ec6d-46e3-abfd- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-PartnerCustomerSubscription], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerSubscription

Does anyone have the same issue ? Do you have a workaround ?
I cannot get those informations from MgGraph.

Thank you

**Comment by marcelbraak** [comment]
Yes, this issue started on january 2nd. The function gives this error on a huge part of our customer base.
You do wisely to migrate over to native REST with the partnercenter API itself. This powershell module isn't updated for NCE  (isn't updated at all for some years)

**Comment by PierreGPOST** [comment]
Yes, i did migrate to REST too and the API, this is the only solution i think.
