### ISSUE TITLE
 Get-PCUsage compatitble command

### ISSUE THREAD

**Issue by VaperWare** [Microsoft/Partner-Center-PowerShell#44]
I'm working on converting our billing module from the previous PartnerCenter version, I'm not finding a command that will return the resourceURI string that get-PCUsage does.

tia for any help

**Comment by isaiahwilliams** [comment]
Hi @VaperWare,

When you invoke the Get-[PartnerCustomerSubscriptionUtilization](https://docs.microsoft.com/powershell/module/partnercenter/partner-center/get-partnercustomersubscriptionutilization?view=partnercenterps-1.5) it will return the resource URI. Are you finding that the value is missing?

**Comment by VaperWare** [comment]
Thanks for the update, I do see the URI information when it's piped to the screen, so I'm probably missing something, but is there not a way to return the URI back to an object for processing ?

**Comment by isaiahwilliams** [comment]
Hi Gerald,

That value is returned as part of the object. So, when you are iterating through the collection of results you will be able to reference it. The current formatting configuration only impacts the default output to the console. All of the underlying properties are still present and can be used as you normally would.

Isaiah Williams
________________________________

**Comment by VaperWare** [comment]
Isaiah, 
Thanks for the clarification, I see them now in the object, a different way of looking at things.

**Comment by VaperWare** [comment]
One last question on this command, is there a reliable way to pull the utilization records to match up to an invoice for URI reconciliation ?

**Comment by isaiahwilliams** [comment]
Hi @VaperWare, 

This feature provides access to the same utilization data that is used to create and calculate the reconciliation file, but it does not have knowledge of billing system reconciliation file logic. Consequently, you should not expect reconciliation file summary results to exactly match the result retrieved from this API for the same time period. There is a possibility it might match, but odds are you will find minor differences between the two. See [Get a customer's utilization records for Azure](https://docs.microsoft.com/partner-center/develop/get-a-customer-s-utilization-record-for-azure) for additional details.
