### ISSUE TITLE
Need some basic help      

### ISSUE THREAD

**Issue by VaperWare** [Microsoft/Partner-Center-PowerShell#48]
I'm having some issues with getting reliable return data, I understand that the data is stored in UTC time correct? now with that understanding I'd to pull data from then system and then match it too the reported data.  Unfortunately the best I can do is to be off by about 2000-3400, I'd be happy with being only off by 500 or less.

report data 11/28/2018 - 12/27/2018

thanks Gerald

**Comment by isaiahwilliams** [comment]
Hi @VaperWare, 

If you are talking about the combination of Azure utilization records with rate card. I would recommend that you check out [Cloud Solution Provider: Consuming Azure utilization records using the Partner Center SDK](https://msuspartner.eventbuilder.com/event?eventid=s4k5p7&source=ocp). While this webinar references the .NET SDK, the logic can still be applied to this PowerShell module.

**Comment by VaperWare** [comment]
Hi, I'm honestly not trying to be a pain, so with that said here's an example of what I'm referring to; 
I first start with setting the date range like this - 
$StartDate = '11/28/2018' ; $EndDate = ' 12/27/2018'
$StartTime = (get-date ((Get-Date $StartDate -Format o).Split("T")[0].ToString() + " 00:00:00")).ToUniversalTime()
$EndTime = (get-date ((Get-Date $EndDate -Format o).Split("T")[0].ToString() + " 23:59:59")).ToUniversalTime()
 
Then I go gather all the records for the billing period, it returns 26,572 records, and then compare the results with the MSFT invoice, there are several missing records for example;

From the invoice summary
ID - f830cae7-d1bd-4f19-b7af-4b2751654bd5
Qty - 721.966686
From the PowerShell cmd
ID - f830cae7-d1bd-4f19-b7af-4b2751654bd5
Qty - 719.966686

Now, I understand that in this example it's only missing two records, but over the course of processing over 25k records it adds up pretty quickly.

Regarding your reference to https://blogs.msdn.microsoft.com/iwilliams/2016/12/19/partner-center-api-and-azure-resource-utilization/, I have been through it several times and I appear to be setting all up correctly.

I look forward to your review/feedback
TIA 
Gerald

**Comment by isaiahwilliams** [comment]
Hi @VaperWare, 

This could be happening for a number of reasons. In most circumstances this has to deal with how the billing generates the invoice. [Get a customer's utilization records for Azure](https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-s-utilization-record-for-azure) covers this in detail. Based on my experince when you are performing these calculations you will not under or over bill in the long run, but the figures between the calculations and the invoice will not always match. I hope that this helps.
