### ISSUE TITLE
New-PartnerCustomerAgreement Breaking change

### ISSUE THREAD

**Issue by slavizh** [Microsoft/Partner-Center-PowerShell#52]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

The command below was working several weeks ago:

```
New-PartnerCustomerAgreement -TemplateId 998b88de-aa99-4388-a42c-1b3517d49490 -AgreementType MicrosoftCloudAgreement -ContactEmail "" -ContactFirstName "" -ContactLastName "" -ContactPhoneNumber "" -CustomerId "" -DateAgreed ([datetime]::ParseExact("2018-11-01","yyyy-MM-dd",$null))
```

When I executed it on the latest version of the module just today I got error:

```
New-PartnerCustomerAgreement : The given key was not present in the dictionary.
At line:1 char:1
+ New-PartnerCustomerAgreement -TemplateId 998b88de-aa99-4388-a42c-1b35 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerCustomerAgreement], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,Microsoft.Store.PartnerCenter.PowerShell
   .Commands.NewPartnerCustomerAgreement
```

## Expected behavior

Expected output was to complete successfully

## Actual behavior

Behavior was error

## Diagnostic logs

Verbose or Debug does not produce any additional information. Seems those were never implemented.
After some testing it is working if you provide valid value for UserId. In documentation UserId is not required parameter and it was working without this parameter several weeks ago as I've tested. Breaking changes should be documented and version should be increased properly when there are such.

## Environment

```
 PartnerCenter 1.5.1812.1 
PS C:\WINDOWS\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  134
```

**Comment by isaiahwilliams** [comment]
Hi @slavizh, 

I have not been able to reproduce this issue. Can you try it again and if the error occurs can you run the following? 

```powershell
$error[0] | Format-List -Force
```

Doing this will provide more details regarding the error.

**Comment by slavizh** [comment]
I've just tried it and same issue. Even tried it on another customer. The tests I am doing are in Sandbox env and I am trying the new authentication model. Could the new auth model affecting this. This is the only thing I've changed since last time I've tested.

![image](https://user-images.githubusercontent.com/11890856/50954938-7b837580-14c0-11e9-8ef1-dfdb866a792f.png)


![image](https://user-images.githubusercontent.com/11890856/50954992-a4a40600-14c0-11e9-921c-36988e157531.png)


```
PS C:\WINDOWS\system32> $error[0] | Format-List -Force


Exception             : System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionar
                        y.
                           at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
                           at Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerCustomerAgreement.ExecuteCmdl
                        et()
                           at Microsoft.Store.PartnerCenter.PowerShell.Commands.PartnerPSCmdlet.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [New-PartnerCustomerAgreement], KeyNotFoundException
FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,Microsoft.Store.PartnerCenter.PowerShell.Comman
                        ds.NewPartnerCustomerAgreement
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

```

**Comment by isaiahwilliams** [comment]
Hi @slavizh, 

Thank you for providing that additional context. You are correct this is an issue caused by the use of the new authentication model. You can work around it by specifying the -UserId parameter when making this call. You will need to get the object identifier for a user from the partner that needs to be associated with the customer consent. I will see what we can do to make this behave in the same manner as it does with the other form of authentication.

**Comment by slavizh** [comment]
Yes. This is what I did. I actually provided the object ID of the app.

**Comment by isaiahwilliams** [comment]
Hi @slavizh, 

I wanted to provide a quick update. The required changes to address this issue have been made. Once the next version is released this issue will be resolved. I currently do not have a time line for when you can expect the next realize. Our hope is to have it ready in early February.

**Comment by slavizh** [comment]
@isaiahwilliams Thanks! I appreciate the update!

**Comment by isaiahwilliams** [comment]
Hi @slavizh, 

The plan is to release a new version this next week that will resolve this issue. I have verified that this issue has been resolved. Please let me know if you discover any other issues.
