### ISSUE TITLE
Get-PartnerCustomerUsageSummary not accepting application credentials 

### ISSUE THREAD

**Issue by VaperWare** [Microsoft/Partner-Center-PowerShell#54]
when I connect to the PartnerCenter using the following connection;
 
$appSecret = $AppKey | ConvertTo-SecureString -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ($AppId, $appSecret)
## Service Principal connection
$oConnectionObject = Connect-PartnerCenter -Credential $credential -ServicePrincipal -TenantId $AuthTenantID

Then trying to use Get-PartnerCustomerUsageSummary to work and then I receive the following message.. 

PS Azure_Source> $CustomerBillingSummary = Get-PartnerCustomerUsageSummary -CustomerId $CustomerId
Get-PartnerCustomerUsageSummary : This resource can't be accessed by application credentials.
At line:1 char:27
+ ... lingSummary = Get-PartnerCustomerUsageSummary -CustomerId $CustomerId
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerUsageSummary], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.
   PowerShell.Commands.GetPartnerCustomerUsageSummary

**Comment by isaiahwilliams** [comment]
Hi @VaperWare, 

This command does not support service principal authentication. You will need to use one of the variations of the [Connect-PartnerCenter](https://docs.microsoft.com/en-us/powershell/module/partnercenter/connect-partnercenter) command that either takes user credentials or an access token to obtain the necessary credentials to perform this operation. 

I would recommend that you review the [secure application model](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model) documentation to get insight into security changes coming to the Partner Center API that will impact this module.

**Comment by isaiahwilliams** [comment]
Hi @VaperWare,

Please feel free to re-open this issue if you have any additional questions. I am going to close it because this ability is not supported using this type of authentication.
