### ISSUE TITLE
Get-PartnerCustomerCompanyProfile output is blank

### ISSUE THREAD

**Issue by Agazoth** [Microsoft/Partner-Center-PowerShell#55]
the cmdlet returns this on all customerids:
Address     :
CompanyName :
Domain      :
Email       :
TenantId    :

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

I have not been able to reproduce this issue. Can you confirm that this is still happening?

**Comment by Agazoth** [comment]
This is still happening. I am using this authentication method:
$credential = Get-Credential
Connect-PartnerCenter -Credential $credential -ServicePrincipal -TenantId '<AppId>'

**Comment by Agazoth** [comment]
When logging on with Connect-PartnerCenter -ApplicationId '<AppId>' however, it works.

**Comment by isaiahwilliams** [comment]
Hi @Agazoth,

Thank you for providing that additional piece of information. To get the customer's company profile you need to authenticate using user credentials. There was a bug in the code that was preventing this error being returned to the console. This issue has been resolve by the changes made through PR #60. 

Right now the plan is to release an updated version of the module in early February. This update will include the updated code to ensure all errors are correctly returned. I really appreicate you providing us this information. Please let us know if you discover any other issues.
