### ISSUE TITLE
Support MFA for App+User Authentication

### ISSUE THREAD

**Issue by corydwood** [Microsoft/Partner-Center-PowerShell#57]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When attempting to run the command below, I receive the error, **Object reference not set to an instance of an object.**

```powershell
New-PartnerAccessToken -ApplicationId <My App ID> -Resource https://api.partnercenter.microsoft.com -TenantId <My Tenant ID>
```

**Describe the solution you would like**
Instead of throwing this error, the interactive login prompt should be displayed asking me to enter my username and password, like it does when using ADAL directly as in the commands below.

```powershell
$authenticationContext = New-Object Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext("https://login.windows.net/$Domain/")
$platformParameters = New-Object Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters -ArgumentList 'Auto'
$token = $authenticationContext.AcquireTokenAsync($ResourceUri, $ApplicationID, 'http://localhost', $platformParameters)
```

**Comment by flyboarder** [comment]
This is a major issue as MS is moving to forced MFA for partners. This module will not function once that change is enable globally.

**Comment by isaiahwilliams** [comment]
Hi Matthew,

Thank you for bringing this issue to my attention. There a handful of updates coming to this process, that will simplify the entire process. You can use the command today to request the appropriate access and refresh token. You can find details at https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

Isaiah Williams
________________________________

**Comment by isaiahwilliams** [comment]
Hi @corydwood and @flyboarder,

You can use the New-PartnerAccess token command to complete the operations defined in the secure application model. There was an issue with running the command using the syntax that you shared. That issue will be resolved with the next version. For more information, see https://docs.microsoft.com/en-us/powershell/partnercenter/install?view=partnercenterps-1.5

**Comment by flyboarder** [comment]
@isaiahwilliams I confirmed that while I am able to generate an access/refresh token - neither will work when authenticating to the partner center API

**Comment by isaiahwilliams** [comment]
@flyboarder, 

Are you calling the Partner Center API directly or are you using the Partner Center PowerShell module?

**Comment by flyboarder** [comment]
@isaiahwilliams Both, I can run the Connect-PartnerCenter, however every response from other funtions returns "unauthorized", unable to authenticate using the tokens via rest api on https://apidocs.microsoft.com/services/partnercenterwebhooks#/RegistrationEvents/RegistrationEvents_Get

**Comment by isaiahwilliams** [comment]
Hi @flyboarder,

Just to confirm you are using the following to generate the refresh token? 

https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

**Comment by flyboarder** [comment]
@isaiahwilliams yes I am able to generate a token successfully using that guide. However the token fails to function.

**Comment by isaiahwilliams** [comment]
Hi @flyboarder, 

Just to confirm you are using the access token value when connecting correct? Also, what version of the Partner Center PowerShell module are you using?

**Comment by flyboarder** [comment]
@isaiahwilliams Yes $token.AccessToken after generating token with the script. Module Versions 1.5.1902.2/1.5.1902.3 I tried updating the module today to see if this would fix the issue. Still not able to use any functions after authenticating.

```
PS $> Connect-PartnerCenter -AccessToken $token.AccessToken

Account            : Microsoft.Store.PartnerCenter.PowerShell.Authentication.AzureAccount
ApplicationId      : *REDACTED*
AuthenticationType : AppOnly
CountryCode        : 
Environment        : GlobalCloud
Locale             : 

PS $> Get-PartnerCustomer

Get-PartnerCustomer : Unauthorized access
At line:1 char:1
+ Get-PartnerCustomer
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomer], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.Power 
   Shell.Commands.GetPartnerCustomer
```

**Comment by isaiahwilliams** [comment]
Hi @flyboarder, 

Thank you for sharing this additional information. It appears that you are using an access token that was generated using app only authentication. If the application is not registered in Partner Center you can see this behavior. Can you verify the web application you are using is registered in Partner Center? 

Also, I wanted to ask when you generate the access token did you use user credentials?
