### ISSUE TITLE
The supplied role does not have the rights to perform the requested operation

### ISSUE THREAD

**Issue by RobBiddle** [Microsoft/Partner-Center-PowerShell#61]
I'm getting errors with most of these cmdlets.
I've tried connecting multiple ways, e.g.:
```PowerShell
$AppCred = Get-Credential -Message 'Username = AppID, Password = App Secret'
$token = New-PartnerAccessToken -Credential $AppCred -Consent -Resource https://api.partnercenter.microsoft.com -ServicePrincipal 
# Entering Global Admin creds when prompted
Connect-PartnerCenter -AccessToken $Token.AccessToken -AccessTokenExpiresOn $Token.ExpiresOn -ApplicationId $appId -TenantId $TenantID
```
OR this way
```PowerShell
$token2 = New-PartnerAccessToken -ApplicationId $appid -Resource https://api.partnercenter.microsoft.com  -TenantId $TenantID -Consent 
# Entering Global Admin creds when prompted
Connect-PartnerCenter -AccessToken $Token2.AccessToken -AccessTokenExpiresOn $Token2.ExpiresOn -ApplicationId $appId -TenantId $TenantID
```
^ Both methods are giving me the same results.

**These cmdlets work**
```PowerShell
Get-PartnerCustomer
```
(Returns all customers as expected)

```PowerShell
Get-PartnerCustomerUser -CustomerId $CustomerTenantID
```
(Returns all users for the customer)

```PowerShell
Get-PartnerCustomerUserLicense -CustomerId $CustomerTenantID-UserId $UserID
```
(Returns the licenses for user in Customer Tenant)

**These cmdlets do not work**
```PowerShell
PS>Get-PartnerCustomerLicenseDeploymentInfo -CustomerId $CustomerTenantID
Get-PartnerCustomerLicenseDeploymentInfo : {
  "Message": "The supplied role does not have the rights to perform the requested operation."
}
At line:1 char:1
+ Get-PartnerCustomerLicenseDeploymentInfo -CustomerId $CustomerTenantID
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerLicenseDeploymentInfo], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerLicenseDeploymentInfo

PS>Get-PartnerCustomerBillingProfile -CustomerId $CustomerTenantID
Get-PartnerCustomerBillingProfile : The supplied role does not have the rights to perform the requested operation.
At line:1 char:1
+ Get-PartnerCustomerBillingProfile -CustomerId $CustomerTenantID
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerBillingProfile], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerBillingProfile

PS>Get-PartnerCustomerUsageSummary -CustomerId $CustomerTenantID
Get-PartnerCustomerUsageSummary : The supplied role does not have the rights to perform the requested operation.
At line:1 char:1
+ Get-PartnerCustomerUsageSummary -CustomerId $CustomerTenantID
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerUsageSummary], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerUsageSummary
```
I'm not sure what I'm doing wrong.

**Comment by isaiahwilliams** [comment]
Hi @RobBiddle, 

Thank you for sharing all of this information. The type of authentication you are using is known as app only. Unfortunately this type of authentication cannot be used with all the operations the Partner Center API supports today. So, to get around this you will need to utilize app + user authentication. Considering the upcoming new security requirements this type of authentication can be tricky. Luckily, we have an article that should help guide you through what needs to be done. See [Partner Center PowerShell | Secure App Model](https://docs.microsoft.com/powershell/partnercenter/secure-app-model) for more information.

**Comment by RobBiddle** [comment]
I just tried this again, following those instructions exactly.  

I used **Create-AzureADApplication.ps1** on that page to create a new Azure AD Application.  Then copy/pasted the commands, using the new AppID/Secret when prompted by the **Get-Credential** cmdlet, and used a Global Admin user (without MFA enabled) when prompted via the Modern Auth login, and I accepted the App consent dialog that followed.

(BTW, the last line of the example is incomplete, **Connect-PartnerCenter** requires **TenantID** as a mandatory parameter.)

Unfortunately the results are the same as in my original post.   :-/

Is there something else that needs to be done in the Customer tenants?
I verified that the Global Admin account I'm using is in the **AdminAgents** group.

It doesn't look like there's any configuration for Partner permissions in the Customer Tenant.  It shows the Parter type as 'Advisor' but it's not configurable.

**Comment by RobBiddle** [comment]
FYI - The MSOnline token based auth on [Partner Center PowerShell | Secure App Model ](https://docs.microsoft.com/powershell/partnercenter/secure-app-model )looks to be working fine.

After following those instructions I can view Subscription info for each tenant using **Get-MsolSubscription**

So it appears that my token auth is working.  However most of the **PartnerCenter** cmdlets are still throwing:

> "The supplied role does not have the rights to perform the requested operation."

**Comment by RobBiddle** [comment]
FYI - I'm using the PSGallery version of this module (1.5.1812.1)

**Comment by isaiahwilliams** [comment]
Hi @RobBiddle,

I believe what you are encountering is the expected behavior for customers with a type of advisor. Can you confirm that you have not established a reseller relationship with the customer in question?

**Comment by RobBiddle** [comment]
I know we don't resell O365 licensing.  My Employer is a Non-Profit and so are our Customers.  Since we don't mark-up the Non-Profit pricing, all licenses are purchased from within the Customer Tenant.  

I'd definitely like clarification on the limits of the Partner Center API.  Resorting to non-delegated accounts would be far from ideal, both in terms of security and ease of automation.  

If I need to push for a different Tenant relationship status I'm happy to do that, but I haven't been able to find any documentation showing that as a necessity.

**Comment by isaiahwilliams** [comment]
Hi @RobBiddle, 

Thank you for sharing this additional information. I will share this feedback with the team behind the API. The command you are attempting to execute will require that you have a reseller relationship that provides deleagated admin privileges over the customer. This is required becuase this operation needs those privilieges to access that information. My recommendation would be to establish a relationship with the customer in question, so you can leverage all features of the Partner Center API. See [Request a reseller relationship](https://docs.microsoft.com/en-us/partner-center/request-a-relationship-with-a-customer) for more information about this process.
