### ISSUE TITLE
New-PartnerCustomerOrder Addon Order throws "2000" error

### ISSUE THREAD

**Issue by jmeilleur1** [Microsoft/Partner-Center-PowerShell#63]
When placing a new order for an Addon to an existing subscription, the following error is thrown
"New-PartnerCustomerOrder : 2000 ParentSubscriptionId is not supported for this request."

## Steps to reproduce
New-PartnerCustomerOrder -CustomerId <customerid guid> -LineItems $lineItems

$LineItems content:
FriendlyName         : Office 365 Advanced Threat Protection
LineItemNumber       : 0
OfferId              : a2706f86-868d-4048-989b-0c69e5c76b63
PartnerIdOnRecord    : 
ParentSubscriptionId : <SubscriptionId of the Parent Exchange Online Plan 1 subscription>
ProvisioningContext  : {}
Quantity             : 31
SubscriptionId       : 

## Expected behavior

> I expect that the order will be placed however, I'm unsure what content the LineItem fields are expecting to purchase a new addon.  This may be a result of not providing the correct data in the PSOrderLineItem object.  Having an example in the help for New-PartnerCustomerOrder where an Addon is being purchased for a parent subscription would be beneficial.

## Actual behavior
Error thrown
"New-PartnerCustomerOrder : 2000 ParentSubscriptionId is not supported for this request."

## Environment
PartnerCenter v1.5.1812.1
PSVersion v5.0.10586.117

**Comment by isaiahwilliams** [comment]
Hi @jmeilleur1, 

This issue will be resolved with the release of version 1.5.1092.5, our hope is to have it available before the end of the week. Thank you for working with us as we address these issues.

**Comment by isaiahwilliams** [comment]
Hi @jmeilleur1, 

We have released version 1.5.1902.5 which includes a fix for this issue. Check out [New-PartnerCustomerOrder](https://docs.microsoft.com/powershell/module/PartnerCenter/New-PartnerCustomerOrder) for an updated example on how to accomplish this.
