### ISSUE TITLE
Connect-PartnerCenter help should be updated to current definition

### ISSUE THREAD

**Issue by Agazoth** [Microsoft/Partner-Center-PowerShell#67]
# Steps to reproduce
Get-Help Connect-PartnerCenter -Examples

NAME
    Connect-PartnerCenter

SYNOPSIS
    Connects to Partner Center with an authenticated account for use with cmdlet requests.

    -------------------------- Example 1 --------------------------

    PS C:\> Connect-PartnerCenter -ApplicationId '<AppId>'

    Connect to Partner Center using the specified application identifier during authentication.
    -------------------------- Example 2 --------------------------

    PS C:\> $credential = Get-Credential
    PS C:\> Connect-PartnerCenter -ApplicationId '<AppId>' -Credential $credential

    Connect to Partner Center using the specified application identifier during authentication.
    -------------------------- Example 3 --------------------------

    PS C:\> $credential = Get-Credential
    PS C:\> Connect-PartnerCenter -Credential $credential -ServicePrincipal -TenantId '<AppId>'

    Connects to Partner Center using app only authentication. When prompted for credential specify the application
    identifier for the username and the application secret for the password.

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
The -ServicePrincipal switch has been removed in version 1.5.1902.1:
Definition          :
                      Connect-PartnerCenter -ApplicationId <string> [-Environment <EnvironmentName>] [-TenantId
                      <string>] [<CommonParameters>]

                      Connect-PartnerCenter -AccessToken <string> -ApplicationId <string> [-Environment
                      <EnvironmentName>] [-TenantId <string>] [<CommonParameters>]

                      Connect-PartnerCenter -Credential <pscredential> -TenantId <string> [-ApplicationId <string>]
                      [-Environment <EnvironmentName>] [<CommonParameters>]

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

Thank you for bringing this to my attention. The necessary changes have been made with the release of version 1.5.1902.2. Please let us know if you find any other issues.
