### ISSUE TITLE
Get-PartnerIndirectReseller : 1002 Authorization Failed

### ISSUE THREAD

**Issue by adrianwells** [Microsoft/Partner-Center-PowerShell#75]
Maybe related to #49?

# Steps to reproduce

Issue the command `Get-Module -Name PartnerCenter`

Using this version:
```

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.5.1902.3 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter...}
```

## Expected behavior

Expect to see a list of indirect resellers

## Actual behavior

Error message
```
Get-PartnerIndirectReseller : 1002 Authorization Failed
At line:1 char:1
+ Get-PartnerIndirectReseller
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerIndirectReseller], PartnerPSException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Exceptions.PartnerPSException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerIndirectReseller
```

## Environment

Windows 10 
PowerShell 5.1

**Comment by isaiahwilliams** [comment]
Hi @adrianwells, 

Just to confirm you are an indirect provider correct?

**Comment by adrianwells** [comment]
@isaiahwilliams , no. Sorry was hoping was curious to see what this reports. Looking for a cmdlet that reports a customer relationship, I understand the cmdlets changed to help clarify.

**Comment by isaiahwilliams** [comment]
Hi @adrianwells,

That particular command will only work for indirect providers. Unfortunately the error returned from the Partner Center API is a bit confusing. Would you mind share what specific information you are seeking?

**Comment by adrianwells** [comment]
@isaiahwilliams thanks for the quick reply. Might there be a cmdlet to report DPOR and DAP information for customers that are configured within MS Partner Center? Maybe something like the cmdlet Get-PartnerCustomerRelationship may have suggested, know it was removed but it'd neat info to have.

**Comment by isaiahwilliams** [comment]
Hi @adrianwells, 

To my knowledge that is not a direct query we can make using the Partner Center API to return this information. You can get run the following 

```powershell
Get-PartnerCustomer | Select CustomerId,Name,RelationshipToPartner
```

This will give you some insight into where the relationship with that customer was established using DAP or the reseller relationship. I hope that this helps.

**Comment by adrianwells** [comment]
@isaiahwilliams - thank you for the reply and information. That is helpful. I will close this issue.
