### ISSUE TITLE
Get-PartnerCustomerUsageSummary : 3000 Customer does not have usage data.

### ISSUE THREAD

**Issue by adrianwells** [Microsoft/Partner-Center-PowerShell#76]
# Steps to reproduce

`Get-PartnerCustomerUsageSummary -CustomerId $CustomerID`

## Expected behavior

Provide Usage Summary, not sure what this should look like as testing so far as produced the same results for different test customers accounts

## Actual behavior

```
Get-PartnerCustomerUsageSummary -CustomerId $CustomerID
Get-PartnerCustomerUsageSummary : 3000 Customer does not have usage data.
At line:1 char:1
+ Get-PartnerCustomerUsageSummary -CustomerId $CustomerID
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerCustomerUsageSummary], PartnerPSException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Exceptions.PartnerPSException,Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerUsageSummary
```

## Environment

Windows 10
PowerShell 5.1
PartnerCenter 1.5.1902.3

**Comment by isaiahwilliams** [comment]
Hi @adrianwells, 

The following is a sample response from this command 

```
Budget           : Microsoft.Store.PartnerCenter.PowerShell.Models.Usage.PSSpendingBudget
ResourceId       : 34f4dcba-b676-475c-a8b9-e5a42b384513
ResourceName     : Test Customer
BillingEndDate   : 2/13/2019 12:00:00 AM +00:00
BillingStartDate : 1/14/2019 12:00:00 AM +00:00
CurrencyLocale   : en-US
LastModifiedDate : 2/11/2019 12:06:09 PM +00:00
TotalCost        : 0.100442
```

With respect to the error you received, does the customer in question have any subscriptions?

**Comment by adrianwells** [comment]
@isaiahwilliams thank you for quick reply and example. Yes, the test customers have subscriptions.

**Comment by isaiahwilliams** [comment]
Hi @adrianwells, 

You will get that error if the customer does not have an Azure subscription. If the customer has an Azure subscription and you are receiving this error, then I would like to encourage you to open a support ticket through Partner Center. Our support organization will be able to help you determine why this is happening if the customer has an Azure subscription.

**Comment by isaiahwilliams** [comment]
Please feel free to re-open this issue if you have any further questions.
