### ISSUE TITLE
'ServicePrincipal' parameter missing from New-PartnerAccessToken

### ISSUE THREAD

**Issue by slavizh** [Microsoft/Partner-Center-PowerShell#79]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.
I am trying to execute the following commands to get token:

```powershell
PS C:\WINDOWS\system32> $token = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://management.azure.com/ -Credential $credential -ServicePrincipal -TenantId $tenantId
New-PartnerAccessToken : A parameter cannot be found that matches parameter name 'ServicePrincipal'.
At line:1 char:125
+ ... nagement.azure.com/ -Credential $credential -ServicePrincipal -Tenant ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PartnerAccessToken], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAcces
   sToken

PS C:\WINDOWS\system32> $graphToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://graph.microsoft.com -Credential $credential -ServicePrincipal -TenantId $tenantId
New-PartnerAccessToken : A parameter cannot be found that matches parameter name 'ServicePrincipal'.
At line:1 char:128
+ ... graph.microsoft.com -Credential $credential -ServicePrincipal -Tenant ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PartnerAccessToken], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAcces
   sToken
```
but I get error:

## Expected behavior

> Share the expected output
Getting token succesfully

## Actual behavior

> What is the behavior observed?

error. Previous version of the module didn't had error with this command. You can also see document updated:
https://github.com/MicrosoftDocs/partner-center-docs-powershell/commit/e06a4a8dd3373884b32eab28a4783931592a8966#diff-6782d3cba88be2eb244513cc067a0d37

When breaking changes are introduce the major version of the module should be increased. So this module should be 2.x.xxxx.x otherwise people will deploy minor versions without actually knowing that breaking changes are introduced. Please start updating the version of the module appropriately. Also start publishing migration guides just how Az/AzureRM does it.

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

provided

## Environment

> Please share additional details about your environment.
> Version

```powershell
PS C:\WINDOWS\system32> Get-Module -ListAvailable -Name PartnerCenter


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.5.1902.3 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserR...

PS C:\WINDOWS\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  134
```

**Comment by slavizh** [comment]
Also now when you try to execute this:

```powershell
$credential = Get-Credential
$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com

cmdlet New-PartnerAccessToken at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
TenantId: ""
```

Tenant ID is required. These are two breaking changes in a single release.

**Comment by isaiahwilliams** [comment]
Hi @slavizh, 

My apologizes about the breaking changes. Going forward we will start handling these changes like the Azure PowerShell module. That way you will receive a warning before the breaking changes are completley implemented. The work required for this change should be completed by early next week at the leasts. Currently there are no immediate plans to introduce any other breaking changes. Please let us know if you encounter any other issues.
