### ISSUE TITLE
Unable to to use set-partnercustomersubscription, PartnerPSException 

### ISSUE THREAD

**Issue by KjeldAntjon** [Microsoft/Partner-Center-PowerShell#81]
# Steps to reproduce

Connect-partnercenter with accesstoken
Everything fails for set-partnercustomersubscription, including the example at https://docs.microsoft.com/en-us/powershell/module/partnercenter/set-partnercustomersubscription?view=partnercenterps-1.5
->
Set-ParnterCustomerSubscription -AutoRenew $false -CustomerId xxx -Subscription xxx (ofcourse with valid custID and SubID.

We're mostly trying to get it to update the quantity of a specific subscription.
I've tried to run the command with the -inputobject $customer.customerId but to no avail.

Other set-x cmdlets do work, set-partnercustomer -custID xxx -email works just fine. 

## Expected behavior

Update the Quantity of a specific subscription

## Actual behavior

Set-PartnerCustomerSubscription :  
At line:1 char:1
+ Set-PartnerCustomerSubscription -CustomerId 7daa9b5f-a076-...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PartnerCustomerSubscription], PartnerPSException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Exceptions.PartnerPSException,Microsoft.Store.PartnerCenter.PowerShell.Commands.SetPartnerCustomer 
   Subscription

PartnerCenter Activity Log is coming up empty, no errors, the successful set commands do show up in the Activity log, and they're executed by the correct user.

## Environment

Created a native app in AAD

Permissions for the app have been as described in https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5
	
Azure Active Directory Graph (3)
Directory.AccessAsUser.All
Delegated
Directory.Read.All
Delegated
User.Read
Delegated
Microsoft Graph (2)
Directory.Read.All
Application
SecurityEvents.Read.All
Application
Microsoft Partner Center (1)
user_impersonation
Delegated

Consent was performed with an account that is an admin agent in Partner Center.
Logon with the with the accesstoken, auth type is AppPlusUser

**Comment by isaiahwilliams** [comment]
Hi @KjeldAntjon, 

This issue will resolved when we release version 1.5.1902.4. Right now our goal is to have this version available in the next day or two.

**Comment by KjeldAntjon** [comment]
Thanks a lot for the quick reply @isaiahwilliams 
Looking forward to it!

**Comment by isaiahwilliams** [comment]
Hi @KjeldAntjon, 

We have released an update that correct this issue. Please update to the latest version, and the problem will be resolved.
