### ISSUE TITLE
Api has more info than Powershell Module

### ISSUE THREAD

**Issue by Crazyabout** [Microsoft/Partner-Center-PowerShell#85]
# Feature Request

**Is your feature request related to a problem? Please describe.**
I want to have more information about the usage than just the id.
In the api respond body in the example I see the resource URi as example. But I can't find any way to get this value per subscription per customer via the Powershell Module

**Describe the solution you would like**
I want the name of my resource because the get PartnerCustomerSubscriptonUsage only provides me the resource id and the category  and subscategory , the name provided in my response is not the name of the actual VM/ Storage account. I think if i somehow got the resource URL( /subscripton/xx/rg/xxx/microsoft.compute/virtualmachine/name) value i could retrieve the name from there. But It seems that this is not possible with the powershell module. While in the documentation in the same powershell command page
https://docs.microsoft.com/en-us/partner-center/develop/get-a-customer-s-utilization-record-for-azure
you can see that the rest api response is more detailed. 

**Describe alternatives you have considered**
I've considered calling the rest api through powershell but I think this would be an overkill as I already use this nice Powershell module

**Comment by Crazyabout** [comment]
The thing i need for my reports is the Resource(vm , storage, ...) name and atm with the powershell module i only got the resourceid. Which is not a good visual on a report. So if anyone knows another way to get the name somehow (the name provided with the get-SubscriptionUtilization is not the name of the resource itself, neither is the name of the command Get-PartnerCustomerSubscriptionUsage)

**Comment by isaiahwilliams** [comment]
Hi @Crazyabout, 

The `Get-PartnerCustomerSubscriptionUsage` command will return a summary of the usage. To get the information you are seeking you will want to invoke the [Get-PartnerCustomerSubscriptionUtilization](https://docs.microsoft.com/powershell/module/partnercenter/get-partnercustomersubscriptionutilization) command. This will return all of the information you need.

**Comment by Crazyabout** [comment]
YES. Was this changed recently because the same command did not gave me any info a couple of weeks ago.
It can be that i got the commands mixed up :D they are so look a like :D
