### ISSUE TITLE
Create a resource uri value inside the command Get-PartnerCustomerSubscriptionUsage

### ISSUE THREAD

**Issue by Crazyabout** [microsoft/Partner-Center-PowerShell#88]
I'm trying to create a report for my customers usage and cost.
This can be all done with the command Get-PartnerCustomerSubscriptionUsage
Only the resourceuri (where i retract the resource name that is visible on the portal) can't be retrieved from this command.

The only command that can retrieve the name is 
`Get-PartnerCustomerSubscriptionUtilization -CustomerId $customerId -SubscriptionId $subscriptionId  -StartDate $Start -EndDate $End -ShowDetails`

But inside this command you've got the usage quantity and unit but no cost.
Is it possible to add also the resource uri to the first command " Get-PartnerCustomerSubscriptionUsage"

If i run both commands on the same subscription I sometimes get 0 query's for the   Get-PartnerCustomerSubscriptionUtilization and a lot of data for the 
Get-PartnerCustomerSubscriptionUsage. Which will give errors for my Report that one customer does not have ResourceUri in their report !!!

**Comment by Crazyabout** [comment]
When I try to get the ResourceUri , based on the id from my usage command 
`  echo $usage[$z].ResourceId
                        if ($usage[$z].ResourceId -eq $array[$z].ResourceID){
                     
                          echo $array[$z].ResourceName
                        }`


I don't seem to get it working :(

**Comment by Crazyabout** [comment]
@isaiahwilliams 
Do you have any idea how i can retrieve the resource name witht the Get-PartnerCustomerSubscriptionUsage.

Or is there a way where you can add the total cost to the Get-PartnerCustomerSubscriptionUtilization api or the resource uri to the Get-PartnerCustomerSubscriptionUsage. 

The resource name provided over there is not the name of the vm or the storage ,.....

**Comment by isaiahwilliams** [comment]
Hi @Crazyabout, 

The resource name is not returned from the API when invoking the Get-PartnerCustomerSubscriptionUsage command. So, unfortunately there is not a way to get the resource name with that command. You will need to use the Get-PartnerCustomerSubscriptionUtilization and Get-PartnerAzureRateCard commands to calculate the price. I would like to encourage you to watch [Cloud Solution Provider: Consuming Azure utilization records using the Partner Center SDK](https://msuspartner.eventbuilder.com/event?eventid=s4k5p7&source=ocp) for details on how this is done. 

Note that recording covers how to use the SDK to perform the operation. You can still use the concepts from that video to build out the process in PowerShell.

**Comment by Crazyabout** [comment]
@isaiahwilliams the problem i have at the moment is that I called the 
Get-PartnerCustomerSubscriptionUsage and the  
Get-PartnerCustomerSubscriptionUtilization command for the same custumor and i saw that Get-PartnerCustomerSubscriptionUsage returned data but  Get-PartnerCustomerSubscriptionUtilization don't .
So that approach will not work :(

**Comment by isaiahwilliams** [comment]
Hi @Crazyabout, 

If you are not getting data back with the [Get-PartnerCustomerSubscriptionUtilization](https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnercustomersubscriptionutilization) command, then I would recommend double checking the start and end date parameters. That command will return the utilization records as they are emitted into the system. 

Currently we do not have a PowerShell command that will combine the rate card and utilization records. However, I can share that this is something that is under consideration.

**Comment by isaiahwilliams** [comment]
Please let us know if you are still having issues.
