### ISSUE TITLE
New-PartnerCustomerOrder throws: 0 The service has encountered an unknown error

### ISSUE THREAD

**Issue by aconn21** [Microsoft/Partner-Center-PowerShell#93]
# Steps to reproduce

Full steps I've used to produce the issue are:

`
#Accept CSP agreement on behalf of customer
    $agreement = Get-PartnerAgreementDetail | Where-Object {$_.AgreementType -eq 'MicrosoftCloudAgreement'} | Select-Object -First 1
    New-PartnerCustomerAgreement -TemplateId $agreement.TemplateId -AgreementType MicrosoftCloudAgreement -CustomerId $newCustomer.Id -ContactEmail 'some@email.com' -ContactFirstName 'Fname' -ContactLastName 'LName'

    # Get offer
    $offer = Get-PartnerOffer -CountryCode 'AU' -OfferId 'MS-AZR-0145P'

    # Create the OrderLineItem
    $lineItem = New-Object -TypeName Microsoft.Store.PartnerCenter.PowerShell.Models.Orders.PSOrderLineItem

    $lineItem.LineItemNumber = 0
    $lineItem.FriendlyName = "Azure - CompanyName"
    $lineItem.OfferId = $offer.id
    $lineItem.Quantity = 1

    #Send Order
    New-PartnerCustomerOrder -CustomerId $newCustomer.Id -LineItems @($lineItem)`

## Expected behavior

Expect it to create an Azure Subscription for the customer

## Actual behavior

throws error: New-PartnerCustomerOrder : 0 The service has encountered an unknown error

At which point, I can still create the Azure subscription via the CSP Web Portal.

## Diagnostic logs

Adding -Debug option to the command doesn't add any useful output.

## Environment

PartnerCenter Module Version: 1.5.1902.5
PowerShell Version: 5.1.14409.1005 
Using Token based authentication, e.g: New-PartnerAccessToken -RefreshToken $RefreshToken -Credential $App_Cred -Resource https://api.partnercenter.microsoft.com -TenantId 'my.domain.com'

**Comment by isaiahwilliams** [comment]
Hi @aconn21, 

When you are populating the line item you need to use `$offer.OfferId` instead of `$offer.id`. Also, since you are creating a new customer using the `New-PartnerCustomer` command, your call to create the order should use $newCustomer.CustomerId` instead of `$newCustomer.Id`

```powershell
# Get offer
$offer = Get-PartnerOffer -CountryCode 'AU' -OfferId 'MS-AZR-0145P'

# Create the OrderLineItem
$lineItem = New-Object -TypeName Microsoft.Store.PartnerCenter.PowerShell.Models.Orders.PSOrderLineItem

$lineItem.LineItemNumber = 0
$lineItem.FriendlyName = "Azure - CompanyName"
$lineItem.OfferId = $offer.OfferId
$lineItem.Quantity = 1

#Send Order
New-PartnerCustomerOrder -CustomerId $newCustomer.CustomerId -LineItems @($lineItem)
```

**Comment by aconn21** [comment]
thanks, have corrected my script.

**Comment by isaiahwilliams** [comment]
I am glad everything is working now. Please let us know if you have any other issues.
